In [1]:
# Upload CSV files into Google Colab
from google.colab import files
uploaded = files.upload()

Saving 2#app_events.csv to 2#app_events.csv
Saving 7#vehicles.csv to 7#vehicles.csv
Saving 3#orders.csv to 3#orders.csv
Saving 9#incidents.csv to 9#incidents.csv
Saving 5#deliveries.csv to 5#deliveries.csv
Saving 1#customers.csv to 1#customers.csv
Saving 8#hubs.csv to 8#hubs.csv
Saving 4#complaints.csv to 4#complaints.csv
Saving 6#drivers.csv to 6#drivers.csv

In [2]:
# Import pandas for data handling
import pandas as pd

# Load all CSV files using entity names
CUSTOMER = pd.read_csv('1#customers.csv')
APP_EVENT = pd.read_csv('2#app_events.csv')
ORDER = pd.read_csv('3#orders.csv')
COMPLAINT = pd.read_csv('4#complaints.csv')
DELIVERY = pd.read_csv('5#deliveries.csv')
DRIVER = pd.read_csv('6#drivers.csv')
VEHICLE = pd.read_csv('7#vehicles.csv')
HUB = pd.read_csv('8#hubs.csv')
INCIDENT = pd.read_csv('9#incidents.csv')

In [3]:
#--------------------CUSTOMER CLEANING------------------------------

In [4]:
#1 Check CUSTOMER structure
CUSTOMER.info()
CUSTOMER.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,27/11/2024 04:25,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,28/10/2025 01:04,55.4,66.6,App,Active
2,C0003,66,East,Consumer,02/07/2025 03:23,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,19/08/2025 01:58,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,03/06/2025 06:02,55.9,100.0,Web,Active

In [5]:
#2 Check missing values in CUSTOMER
CUSTOMER.isnull().sum()

customer_id              0
age                      0
home_zone                0
customer_type            0
signup_date              0
loyalty_score           20
app_engagement_score     0
preferred_channel       13
account_status           0
dtype: int64

In [6]:
#3 Remove duplicate rows
CUSTOMER = CUSTOMER.drop_duplicates()

In [7]:
#4 Standardise text columns
CUSTOMER['home_zone'] = CUSTOMER['home_zone'].str.strip().str.title()
CUSTOMER['home_zone'] = CUSTOMER['home_zone'].replace({'Ctr': 'Central'})

CUSTOMER['customer_type'] = CUSTOMER['customer_type'].str.strip().str.title()
CUSTOMER['preferred_channel'] = CUSTOMER['preferred_channel'].str.strip()
CUSTOMER['account_status'] = CUSTOMER['account_status'].str.strip().str.title()

In [8]:
#5 Convert signup date into datetime format
CUSTOMER['signup_date'] = pd.to_datetime(CUSTOMER['signup_date'], errors='coerce')

/tmp/ipykernel_2837/1332903111.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  CUSTOMER['signup_date'] = pd.to_datetime(CUSTOMER['signup_date'], errors='coerce')

In [9]:
#6.1 Fill missing loyalty score using median
CUSTOMER['loyalty_score'] = CUSTOMER['loyalty_score'].fillna(CUSTOMER['loyalty_score'].median())

#6.2 Fill missing preferred channel using Unknown
CUSTOMER['preferred_channel'] = CUSTOMER['preferred_channel'].fillna('Unknown')

In [10]:
#7 Create customer age group column
CUSTOMER['age_group'] = pd.cut(
    CUSTOMER['age'],
    bins=[0, 25, 40, 60, 100],
    labels=['Young', 'Adult', 'Middle_Aged', 'Senior']
)

In [11]:
#--------------------APP_EVENT CLEANING------------------------------

In [12]:
#1 Check APP_EVENT structure
APP_EVENT.info()
APP_EVENT.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    object
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: int64(2), object(8)
memory usage: 50.1+ KB

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,09/08/2024 03:25,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,13/02/2024 22:29,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,11/08/2025 09:29,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,23/08/2025 17:38,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,29/05/2024 10:33,search_route,S12030,iOS,north,60,1

In [13]:
#2 Check missing values in APP_EVENT
APP_EVENT.isnull().sum()

event_id             0
customer_id          0
order_id           144
event_timestamp      0
event_type           0
session_id           0
device_type          0
zone_context         0
api_latency_ms       0
success_flag         0
dtype: int64

In [14]:
#3 Remove duplicate rows
APP_EVENT = APP_EVENT.drop_duplicates()

In [15]:
#4 Standardise text columns
APP_EVENT['event_type'] = APP_EVENT['event_type'].str.strip().str.lower()
APP_EVENT['device_type'] = APP_EVENT['device_type'].str.strip()

APP_EVENT['zone_context'] = APP_EVENT['zone_context'].str.strip().str.title()
APP_EVENT['zone_context'] = APP_EVENT['zone_context'].replace({'Ctr': 'Central'})

In [16]:
#5 Convert event timestamp into datetime format
APP_EVENT['event_timestamp'] = pd.to_datetime(APP_EVENT['event_timestamp'], errors='coerce')

In [17]:
#6 Handle missing order_id
APP_EVENT['order_id'] = APP_EVENT['order_id'].fillna('No_Order_Link')

In [18]:
#7 Create event success status column
APP_EVENT['event_success_status'] = APP_EVENT['success_flag'].map({
    1: 'Success',
    0: 'Failed'
})

In [19]:
#8 Create latency category column
APP_EVENT['latency_category'] = pd.cut(
    APP_EVENT['api_latency_ms'],
    bins=[0, 100, 300, 10000],
    labels=['Low', 'Medium', 'High']
)

In [20]:
#------------------------ORDER CLEANING-----------------------------------

In [21]:
#1 Check ORDER structure
ORDER.info()
ORDER.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,20/08/2024 14:43,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,14/05/2024 22:16,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,02/09/2025 14:37,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,11/01/2025 17:15,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,17/02/2025 19:32,12,Riverside,SOUTH,Low,125.58,Phone,0

In [22]:
#2 Check missing values in ORDER
ORDER.isnull().sum()

order_id                  0
customer_id               0
service_type              0
order_created_at          0
promised_window_hours     0
pickup_zone               0
dropoff_zone              0
priority_level            0
order_value               0
booking_channel          25
special_handling_flag     0
dtype: int64

In [23]:
#3 Remove duplicate rows
ORDER = ORDER.drop_duplicates()

In [24]:
#4 Standardise text columns
ORDER['service_type'] = ORDER['service_type'].str.strip().str.title()
ORDER['pickup_zone'] = ORDER['pickup_zone'].str.strip().str.title()
ORDER['dropoff_zone'] = ORDER['dropoff_zone'].str.strip().str.title()

ORDER['pickup_zone'] = ORDER['pickup_zone'].replace({'Ctr': 'Central'})
ORDER['dropoff_zone'] = ORDER['dropoff_zone'].replace({'Ctr': 'Central'})

ORDER['priority_level'] = ORDER['priority_level'].str.strip().str.title()
ORDER['booking_channel'] = ORDER['booking_channel'].str.strip()

In [25]:
#5 Convert order created date into datetime format
ORDER['order_created_at'] = pd.to_datetime(ORDER['order_created_at'], errors='coerce')

/tmp/ipykernel_2837/2643839832.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ORDER['order_created_at'] = pd.to_datetime(ORDER['order_created_at'], errors='coerce')

In [26]:
#6 Fill missing booking channel using Unknown
ORDER['booking_channel'] = ORDER['booking_channel'].fillna('Unknown')

In [27]:
#7 Create high value order flag
ORDER['high_value_order'] = ORDER['order_value'] > ORDER['order_value'].median()

In [28]:
#-----------------COMPLAINT CLEANING--------------------------------

In [29]:
#1 Check COMPLAINT structure
COMPLAINT.info()
COMPLAINT.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    object
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 25.1+ KB

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,30/03/2025 02:36,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,07/11/2024 10:05,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,02/01/2024 15:47,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,14/01/2025 13:07,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,31/08/2024 05:56,Resolved,1,16.18

In [30]:
#2 Check missing values in COMPLAINT
COMPLAINT.isnull().sum()

complaint_id            0
customer_id             0
order_id                0
complaint_type          0
channel                 0
severity                0
created_at              0
status                  0
resolution_days         0
compensation_amount    16
dtype: int64

In [31]:
#3 Remove duplicate rows
COMPLAINT = COMPLAINT.drop_duplicates()

In [32]:
#4 Standardise text columns
COMPLAINT['complaint_type'] = COMPLAINT['complaint_type'].str.strip().str.title()
COMPLAINT['channel'] = COMPLAINT['channel'].str.strip()
COMPLAINT['severity'] = COMPLAINT['severity'].str.strip().str.title()
COMPLAINT['status'] = COMPLAINT['status'].str.strip().str.title()

In [33]:
#5 Convert complaint created date into datetime format
COMPLAINT['created_at'] = pd.to_datetime(COMPLAINT['created_at'], errors='coerce')

/tmp/ipykernel_2837/3083332313.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  COMPLAINT['created_at'] = pd.to_datetime(COMPLAINT['created_at'], errors='coerce')

In [34]:
#6 Fill missing compensation amount with 0
COMPLAINT['compensation_amount'] = COMPLAINT['compensation_amount'].fillna(0)

In [35]:
#7 Create complaint resolved flag
COMPLAINT['is_resolved'] = COMPLAINT['status'].apply(
    lambda x: 1 if x == 'Resolved' else 0
)

In [36]:
#-------------------DELIVERY CLEANING----------------------------------

In [37]:
#1 Check DELIVERY structure
DELIVERY.info()
DELIVERY.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,18/06/2024 10:57,05:59.9,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,11/01/2025 18:45,39:00.0,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,02/06/2025 20:39,45:32.4,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,08/03/2024 23:31,30:08.1,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,21/09/2025 11:43,45:34.1,OnTime,14.52,1,0,4.18,9.22

In [38]:
#2 Check missing values in DELIVERY
DELIVERY.isnull().sum()

delivery_id                       0
order_id                          0
driver_id                         0
vehicle_id                        0
hub_id                            0
dispatch_time                     0
delivery_completed_at            19
delivery_status                   0
route_distance_km                 0
manual_route_override_count       0
proof_of_completion_missing       0
customer_rating_post_delivery    14
fuel_or_charge_cost               0
dtype: int64

In [39]:
#3 Remove duplicate rows
DELIVERY = DELIVERY.drop_duplicates()

In [40]:
#4 Standardise text columns
DELIVERY['delivery_status'] = DELIVERY['delivery_status'].str.strip().str.title()

In [41]:
#5 Convert delivery dates into datetime format
DELIVERY['dispatch_time'] = pd.to_datetime(DELIVERY['dispatch_time'], errors='coerce')
DELIVERY['delivery_completed_at'] = pd.to_datetime(DELIVERY['delivery_completed_at'], errors='coerce')

/tmp/ipykernel_2837/3166721641.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  DELIVERY['dispatch_time'] = pd.to_datetime(DELIVERY['dispatch_time'], errors='coerce')
/tmp/ipykernel_2837/3166721641.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  DELIVERY['delivery_completed_at'] = pd.to_datetime(DELIVERY['delivery_completed_at'], errors='coerce')

In [42]:
#6 Fill missing customer ratings using median
DELIVERY['customer_rating_post_delivery'] = DELIVERY['customer_rating_post_delivery'].fillna(
    DELIVERY['customer_rating_post_delivery'].median()
)

In [43]:
#7 Keep missing completion time as blank (for failed deliveries)
# No fill applied to delivery_completed_at

In [44]:
#8 Create delivery duration in hours
DELIVERY['delivery_duration_hours'] = (
    DELIVERY['delivery_completed_at'] - DELIVERY['dispatch_time']
).dt.total_seconds() / 3600

In [45]:
#9 Create failed delivery flag
DELIVERY['failed_delivery_flag'] = DELIVERY['delivery_status'].apply(
    lambda x: 1 if x == 'Failed' else 0
)

In [46]:
#10 Create delayed delivery flag
DELIVERY['delayed_delivery_flag'] = DELIVERY['delivery_status'].apply(
    lambda x: 1 if x == 'Delayed' else 0
)

In [47]:
#-------------------DRIVER CLEANING------------------------------

In [48]:
#1 Check DRIVER structure
DRIVER.info()
DRIVER.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

In [49]:
#2 Check missing values in DRIVER
DRIVER.isnull().sum()

driver_id           0
base_zone           0
employment_type     0
years_experience    0
training_score      7
driver_rating       0
shift_preference    0
active_flag         0
dtype: int64

In [50]:
#3 Remove duplicate rows
DRIVER = DRIVER.drop_duplicates()

In [51]:
#4 Standardise text columns
DRIVER['base_zone'] = DRIVER['base_zone'].str.strip().str.title()
DRIVER['base_zone'] = DRIVER['base_zone'].replace({'Ctr': 'Central'})

DRIVER['employment_type'] = DRIVER['employment_type'].str.strip().str.title()
DRIVER['shift_preference'] = DRIVER['shift_preference'].str.strip().str.title()

In [52]:
#5 Fill missing training score using median
DRIVER['training_score'] = DRIVER['training_score'].fillna(
    DRIVER['training_score'].median()
)

In [53]:
#6 Create driver experience level column
DRIVER['experience_level'] = pd.cut(
    DRIVER['years_experience'],
    bins=[-1, 2, 5, 10, 50],
    labels=['New', 'Intermediate', 'Experienced', 'Senior']
)

In [54]:
#-----------------------------VEHICLE CLEANING-----------------------

In [55]:
#1 Check VEHICLE structure
VEHICLE.info()
VEHICLE.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,28/12/2024 23:48,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,21/04/2024 16:14,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,24/11/2025 23:59,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,07/06/2024 13:21,NaN,36310,Active,v2.2
4,V005,CargoVan,West,15/11/2025 11:08,58.6,146638,Active,v2.2

In [56]:
#2 Check missing values in VEHICLE
VEHICLE.isnull().sum()

vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    4
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64

In [57]:
#3 Remove duplicate rows
VEHICLE = VEHICLE.drop_duplicates()

In [58]:
#4 Standardise text columns
VEHICLE['vehicle_type'] = VEHICLE['vehicle_type'].str.strip().str.title()

VEHICLE['assigned_zone'] = VEHICLE['assigned_zone'].str.strip().str.title()
VEHICLE['assigned_zone'] = VEHICLE['assigned_zone'].replace({'Ctr': 'Central'})

VEHICLE['maintenance_status'] = VEHICLE['maintenance_status'].str.strip().str.title()
VEHICLE['telematics_version'] = VEHICLE['telematics_version'].str.strip()

In [59]:
#5 Convert commission date into datetime format
VEHICLE['commission_date'] = pd.to_datetime(VEHICLE['commission_date'], errors='coerce')

/tmp/ipykernel_2837/313132213.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  VEHICLE['commission_date'] = pd.to_datetime(VEHICLE['commission_date'], errors='coerce')

In [60]:
#6 Fill missing battery health using median
VEHICLE['battery_health_pct'] = VEHICLE['battery_health_pct'].fillna(
    VEHICLE['battery_health_pct'].median()
)

In [61]:
#7 Create battery health category
VEHICLE['battery_health_category'] = pd.cut(
    VEHICLE['battery_health_pct'],
    bins=[0, 60, 80, 100],
    labels=['Low', 'Medium', 'High']
)

In [62]:
#----------------------------HUB CLEANING-------------------------------

In [63]:
#1 Check HUB structure
HUB.info()
HUB.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88

In [64]:
#2 Check missing values in HUB
HUB.isnull().sum()

hub_id            0
hub_name          0
zone              0
hub_type          0
capacity_score    0
dtype: int64

In [65]:
#3 Remove duplicate rows
HUB = HUB.drop_duplicates()

In [66]:
#4 Standardise text columns
HUB['hub_name'] = HUB['hub_name'].str.strip().str.title()
HUB['zone'] = HUB['zone'].str.strip().str.title()
HUB['hub_type'] = HUB['hub_type'].str.strip().str.title()

In [67]:
#5 Create hub capacity category
HUB['capacity_category'] = pd.cut(
    HUB['capacity_score'],
    bins=[0, 50, 75, 100],
    labels=['Low', 'Medium', 'High']
)

In [68]:
#--------------------INCIDENT CLEANING--------------------------------

In [69]:
#1 Check INCIDENT structure
INCIDENT.info()
INCIDENT.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    object
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: float64(1), object(6)
memory usage: 15.4+ KB

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,11/03/2024 23:46,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,21/02/2024 10:56,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,17/04/2025 23:22,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,09/02/2025 00:16,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,04/01/2025 02:49,Low,Open,13.0

In [70]:
#2 Check missing values in INCIDENT
INCIDENT.isnull().sum()

incident_id           0
delivery_id           0
incident_type         0
reported_at           0
severity              0
resolution_status     0
resolved_hours       17
dtype: int64

In [71]:
#3 Remove duplicate rows
INCIDENT = INCIDENT.drop_duplicates()

In [72]:
#4 Standardise text columns
INCIDENT['incident_type'] = INCIDENT['incident_type'].str.strip().str.title()
INCIDENT['severity'] = INCIDENT['severity'].str.strip().str.title()
INCIDENT['resolution_status'] = INCIDENT['resolution_status'].str.strip().str.title()

In [73]:
#5 Convert reported date into datetime format
INCIDENT['reported_at'] = pd.to_datetime(INCIDENT['reported_at'], errors='coerce')

In [74]:
#6 Fill missing resolved hours with median
INCIDENT['resolved_hours'] = INCIDENT['resolved_hours'].fillna(
    INCIDENT['resolved_hours'].median()
)

In [75]:
#7 Create unresolved incident flag
INCIDENT['unresolved_flag'] = INCIDENT['resolution_status'].apply(
    lambda x: 1 if x in ['Open', 'Escalated', 'Pendingvendor'] else 0
)

In [76]:
#-------------------------------------------------------------

In [77]:
# Final check for missing values and duplicates in all datasets

datasets = {
    "CUSTOMER": CUSTOMER,
    "APP_EVENT": APP_EVENT,
    "ORDER": ORDER,
    "COMPLAINT": COMPLAINT,
    "DELIVERY": DELIVERY,
    "DRIVER": DRIVER,
    "VEHICLE": VEHICLE,
    "HUB": HUB,
    "INCIDENT": INCIDENT
}

for name, df in datasets.items():
    print(f"\n{name} DATASET CHECK")

    # Check missing values
    print("\nMissing Values:")
    print(df.isnull().sum())

    # Check duplicates
    print("\nDuplicate Rows:", df.duplicated().sum())

CUSTOMER DATASET CHECK

Missing Values:
customer_id             0
age                     0
home_zone               0
customer_type           0
signup_date             0
loyalty_score           0
app_engagement_score    0
preferred_channel       0
account_status          0
age_group               0
dtype: int64

Duplicate Rows: 0

APP_EVENT DATASET CHECK

Missing Values:
event_id                  0
customer_id               0
order_id                  0
event_timestamp         381
event_type                0
session_id                0
device_type               0
zone_context              0
api_latency_ms            0
success_flag              0
event_success_status      0
latency_category          0
dtype: int64

Duplicate Rows: 0

ORDER DATASET CHECK

Missing Values:
order_id                 0
customer_id              0
service_type             0
order_created_at         0
promised_window_hours    0
pickup_zone              0
dropoff_zone             0
priority_level           0
order_value              0
booking_channel          0
special_handling_flag    0
high_value_order         0
dtype: int64

Duplicate Rows: 0

COMPLAINT DATASET CHECK

Missing Values:
complaint_id           0
customer_id            0
order_id               0
complaint_type         0
channel                0
severity               0
created_at             0
status                 0
resolution_days        0
compensation_amount    0
is_resolved            0
dtype: int64

Duplicate Rows: 0

DELIVERY DATASET CHECK

Missing Values:
delivery_id                        0
order_id                           0
driver_id                          0
vehicle_id                         0
hub_id                             0
dispatch_time                      0
delivery_completed_at            588
delivery_status                    0
route_distance_km                  0
manual_route_override_count        0
proof_of_completion_missing        0
customer_rating_post_delivery      0
fuel_or_charge_cost                0
delivery_duration_hours          588
failed_delivery_flag               0
delayed_delivery_flag              0
dtype: int64

Duplicate Rows: 0

DRIVER DATASET CHECK

Missing Values:
driver_id           0
base_zone           0
employment_type     0
years_experience    0
training_score      0
driver_rating       0
shift_preference    0
active_flag         0
experience_level    0
dtype: int64

Duplicate Rows: 0

VEHICLE DATASET CHECK

Missing Values:
vehicle_id                 0
vehicle_type               0
assigned_zone              0
commission_date            0
battery_health_pct         0
odometer_km                0
maintenance_status         0
telematics_version         0
battery_health_category    0
dtype: int64

Duplicate Rows: 0

HUB DATASET CHECK

Missing Values:
hub_id               0
hub_name             0
zone                 0
hub_type             0
capacity_score       0
capacity_category    0
dtype: int64

Duplicate Rows: 0

INCIDENT DATASET CHECK

Missing Values:
incident_id            0
delivery_id            0
incident_type          0
reported_at          163
severity               0
resolution_status      0
resolved_hours         0
unresolved_flag        0
dtype: int64

Duplicate Rows: 0

In [78]:
# Additional structure check

for name, df in datasets.items():
    print(f"\n{name} INFO")
    df.info()

    print("\nSample Data:")
    display(df.head())

CUSTOMER INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    datetime64[ns]
 5   loyalty_score         650 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     650 non-null    object
 8   account_status        650 non-null    object
 9   age_group             650 non-null    category
dtypes: category(1), datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 46.7+ KB

Sample Data:

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status,age_group
0,C0001,26,North,Sme,2024-11-27 04:25:00,44.9,69.2,App,Active,Adult
1,C0002,61,Airport,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active,Senior
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,Unknown,Active,Senior
3,C0004,75,Central,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active,Senior
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active,Adult

APP_EVENT INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_id              640 non-null    object
 1   customer_id           640 non-null    object
 2   order_id              640 non-null    object
 3   event_timestamp       259 non-null    datetime64[ns]
 4   event_type            640 non-null    object
 5   session_id            640 non-null    object
 6   device_type           640 non-null    object
 7   zone_context          640 non-null    object
 8   api_latency_ms        640 non-null    int64
 9   success_flag          640 non-null    int64
 10  event_success_status  640 non-null    object
 11  latency_category      640 non-null    category
dtypes: category(1), datetime64[ns](1), int64(2), object(8)
memory usage: 55.9+ KB

Sample Data:

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag,event_success_status,latency_category
0,AE00001,C0488,No_Order_Link,2024-09-08 03:25:00,eta_refresh,S19847,Android,North,301,1,Success,High
1,AE00002,C0595,O00950,NaT,search_route,S32766,Android,South,60,1,Success,Low
2,AE00003,C0494,O00170,2025-11-08 09:29:00,chat_opened,S99516,iOS,Airport,1118,1,Success,High
3,AE00004,C0407,O00756,NaT,eta_refresh,S41236,iOS,Central,442,1,Success,High
4,AE00005,C0506,No_Order_Link,NaT,search_route,S12030,iOS,North,60,1,Success,Low

ORDER INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   datetime64[ns]
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1250 non-null   object
 10  special_handling_flag  1250 non-null   int64
 11  high_value_order       1250 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2), object(7)
memory usage: 108.8+ KB

Sample Data:

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag,high_value_order
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0,True
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,Airport,Low,109.30,App,0,True
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,Airport,High,33.50,Phone,0,False
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,Riverside,North,Medium,10.04,App,1,False
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,South,Low,125.58,Phone,0,True

COMPLAINT INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    datetime64[ns]
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  320 non-null    float64
 10  is_resolved          320 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(7)
memory usage: 27.6+ KB

Sample Data:

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount,is_resolved
0,CP0001,C0464,O00814,Appissue,App,High,2025-03-30 02:36:00,Open,11,23.99,0
1,CP0002,C0056,O00628,Missedpickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64,0
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41,0
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,Awaitingcustomer,7,23.44,0
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18,1

DELIVERY INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    datetime64[ns]
 6   delivery_completed_at          362 non-null    datetime64[ns]
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  950 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
 13  delivery_duration_hours        362 non-null    float64
 14  failed_delivery_flag           950 non-null    int64
 15  delayed_delivery_flag          950 non-null    int64
dtypes: datetime64[ns](2), float64(4), int64(4), object(6)
memory usage: 118.9+ KB

Sample Data:

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost,delivery_duration_hours,failed_delivery_flag,delayed_delivery_flag
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2026-04-28 05:59:54,Failed,17.26,1,0,3.07,12.05,16291.048333,1,0
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,NaT,Ontime,10.34,1,0,5.00,13.41,NaN,0,0
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,NaT,Ontime,7.92,0,0,4.98,8.51,NaN,0,0
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,NaT,Delayed,16.42,0,0,4.18,13.62,NaN,0,1
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,NaT,Ontime,14.52,1,0,4.18,9.22,NaN,0,0

DRIVER INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    170 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
 8   experience_level  170 non-null    category
dtypes: category(1), float64(2), int64(2), object(4)
memory usage: 11.1+ KB

Sample Data:

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag,experience_level
0,D001,Airport,Fulltime,8,67.8,3.54,Morning,1,Experienced
1,D002,Central,Fulltime,4,42.4,3.94,Evening,1,Intermediate
2,D003,Airport,Fulltime,11,96.5,5.00,Evening,1,Senior
3,D004,Airport,Parttime,13,88.9,4.75,Morning,1,Senior
4,D005,North,Fulltime,3,69.7,4.14,Morning,1,Intermediate

VEHICLE INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   vehicle_id               120 non-null    object
 1   vehicle_type             120 non-null    object
 2   assigned_zone            120 non-null    object
 3   commission_date          120 non-null    datetime64[ns]
 4   battery_health_pct       120 non-null    float64
 5   odometer_km              120 non-null    int64
 6   maintenance_status       120 non-null    object
 7   telematics_version       120 non-null    object
 8   battery_health_category  120 non-null    category
dtypes: category(1), datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 7.9+ KB

Sample Data:

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version,battery_health_category
0,V001,Ev,North,2024-12-28 23:48:00,71.80,56928,Active,v2.2,Medium
1,V002,Ev,Airport,2024-04-21 16:14:00,67.90,159368,Inrepair,v2.2,Medium
2,V003,Cargovan,North,2025-11-24 23:59:00,91.70,219359,Active,v2.1,High
3,V004,Hybrid,Riverside,2024-06-07 13:21:00,78.05,36310,Active,v2.2,Medium
4,V005,Cargovan,West,2025-11-15 11:08:00,58.60,146638,Active,v2.2,Low

HUB INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hub_id             8 non-null      object
 1   hub_name           8 non-null      object
 2   zone               8 non-null      object
 3   hub_type           8 non-null      object
 4   capacity_score     8 non-null      int64
 5   capacity_category  8 non-null      category
dtypes: category(1), int64(1), object(4)
memory usage: 592.0+ bytes

Sample Data:

  hub_id        hub_name     zone   hub_type  capacity_score capacity_category
0    H01  North Exchange    North   Dispatch              82              High
1    H02      South Link    South   Dispatch              78              High
2    H03       East Dock     East  Warehouse              74            Medium
3    H04       West Gate     West   Dispatch              69            Medium
4    H05    Central Core  Central    Control              88              High

INCIDENT INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        117 non-null    datetime64[ns]
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     280 non-null    float64
 7   unresolved_flag    280 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 17.6+ KB

Sample Data:

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours,unresolved_flag
0,I0001,DL00221,Batteryalert,2024-11-03 23:46:00,Medium,Escalated,12.3,1
1,I0002,DL00578,Batteryalert,NaT,Low,Open,9.6,1
2,I0003,DL00175,Temperatureissue,NaT,Medium,Open,22.0,1
3,I0004,DL00417,Proofmissing,2025-09-02 00:16:00,Medium,Closed,9.8,0
4,I0005,DL00897,Routedeviation,2025-04-01 02:49:00,Low,Open,13.0,1

In [79]:
# Save cleaned datasets as new CSV files
CUSTOMER.to_csv('1#clean_customers.csv', index=False)
APP_EVENT.to_csv('2#clean_app_events.csv', index=False)
ORDER.to_csv('3#clean_orders.csv', index=False)
COMPLAINT.to_csv('4#clean_complaints.csv', index=False)
DELIVERY.to_csv('5#clean_deliveries.csv', index=False)
DRIVER.to_csv('6#clean_drivers.csv', index=False)
VEHICLE.to_csv('7#clean_vehicles.csv', index=False)
HUB.to_csv('8#clean_hubs.csv', index=False)
INCIDENT.to_csv('9#clean_incidents.csv', index=False)

In [80]:
# Download cleaned files to computer locally
from google.colab import files

files.download('1#clean_customers.csv')
files.download('2#clean_app_events.csv')
files.download('3#clean_orders.csv')
files.download('4#clean_complaints.csv')
files.download('5#clean_deliveries.csv')
files.download('6#clean_drivers.csv')
files.download('7#clean_vehicles.csv')
files.download('8#clean_hubs.csv')
files.download('9#clean_incidents.csv')