<a href="https://colab.research.google.com/github/Mohommad-Nuzlan-GH/M-R-M-Nuzlan-Database-Analytics-Top-Up-2026/blob/main/2_SQL_in_R_NS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Upload cleaned CSV files into Google Colab
files <- file.choose()

In [ ]:
# Install packages needed for SQL in R
install.packages("sqldf")
install.packages("dplyr")

# Load packages
library(sqldf)
library(dplyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
# Load cleaned datasets into R
CUSTOMER <- read.csv("1#clean_customers.csv")
APP_EVENT <- read.csv("2#clean_app_events.csv")
ORDER_DATA <- read.csv("3#clean_orders.csv")
COMPLAINT <- read.csv("4#clean_complaints.csv")
DELIVERY <- read.csv("5#clean_deliveries.csv")
DRIVER <- read.csv("6#clean_drivers.csv")
VEHICLE <- read.csv("7#clean_vehicles.csv")
HUB <- read.csv("8#clean_hubs.csv")
INCIDENT <- read.csv("9#clean_incidents.csv")

In [ ]:
# Check first rows of each main dataset
head(CUSTOMER)
head(ORDER_DATA)
head(DELIVERY)

  customer_id age home_zone customer_type signup_date      loyalty_score
1 C0001       26  North     Sme           27/11/2024 04:25 44.9
2 C0002       61  Airport   Consumer      28/10/2025 01:04 55.4
3 C0003       66  East      Consumer      02/07/2025 03:23 75.9
4 C0004       75  Central   Consumer      19/08/2025 01:58 32.5
5 C0005       26  Riverside Consumer      03/06/2025 06:02 55.9
6 C0006       41  West      Consumer      29/03/2024 13:26 39.9
  app_engagement_score preferred_channel account_status age_group
1  69.2                App               Active         Adult
2  66.6                App               Active         Senior
3  33.8                Unknown           Active         Senior
4  33.0                App               Active         Senior
5 100.0                Web               Active         Adult
6  43.3                Web               Active         Middle_Aged

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       Airport      Low            109.30      App
3 West        Airport      High            33.50      Phone
4 Riverside   North        Medium          10.04      App
5 Riverside   South        Low            125.58      Phone
6 Central     East         High           151.44      Web
  special_handling_flag high_value_order
1 0                     True
2 0                     True
3 0                     False
4 1                     False
5 0                     True
6 1                     True

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at delivery_status route_distance_km
1 2026-04-28 05:59:54   Failed          17.26
2                       Ontime          10.34
3                       Ontime           7.92
4                       Delayed         16.42
5                       Ontime          14.52
6 2026-04-28 11:52:24   Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost delivery_duration_hours
1 3.07                          12.05               16291.05
2 5.00                          13.41                     NA
3 4.98                           8.51                     NA
4 4.18                          13.62                     NA
5 4.18                           9.22                     NA
6 1.57                           9.58               14255.21
  failed_delivery_flag delayed_delivery_flag
1 1                    0
2 0                    0
3 0                    0
4 0                    1
5 0                    0
6 0                    1

In [ ]:
# Check dataset structure
str(CUSTOMER)
str(ORDER_DATA)
str(DELIVERY)

'data.frame':	650 obs. of  10 variables:
 $ customer_id         : chr  "C0001" "C0002" "C0003" "C0004" ...
 $ age                 : int  26 61 66 75 26 41 54 70 34 23 ...
 $ home_zone           : chr  "North" "Airport" "East" "Central" ...
 $ customer_type       : chr  "Sme" "Consumer" "Consumer" "Consumer" ...
 $ signup_date         : chr  "27/11/2024 04:25" "28/10/2025 01:04" "02/07/2025 03:23" "19/08/2025 01:58" ...
 $ loyalty_score       : num  44.9 55.4 75.9 32.5 55.9 39.9 36.1 84.6 62.6 87.2 ...
 $ app_engagement_score: num  69.2 66.6 33.8 33 100 43.3 39 65.2 40.8 48.6 ...
 $ preferred_channel   : chr  "App" "App" "Unknown" "App" ...
 $ account_status      : chr  "Active" "Active" "Active" "Active" ...
 $ age_group           : chr  "Adult" "Senior" "Senior" "Senior" ...
'data.frame':	1250 obs. of  12 variables:
 $ order_id             : chr  "O00001" "O00002" "O00003" "O00004" ...
 $ customer_id          : chr  "C0292" "C0459" "C0161" "C0520" ...
 $ service_type         : chr  "Passenger" "Passenger" "Passenger" "Parcel" ...
 $ order_created_at     : chr  "2024-08-20 14:43:00" "2024-05-14 22:16:00" "2025-09-02 14:37:00" "2025-01-11 17:15:00" ...
 $ promised_window_hours: int  6 24 4 2 12 1 2 4 12 6 ...
 $ pickup_zone          : chr  "Airport" "North" "West" "Riverside" ...
 $ dropoff_zone         : chr  "South" "Airport" "Airport" "North" ...
 $ priority_level       : chr  "Medium" "Low" "High" "Medium" ...
 $ order_value          : num  126.7 109.3 33.5 10 125.6 ...
 $ booking_channel      : chr  "App" "App" "Phone" "App" ...
 $ special_handling_flag: int  0 0 0 1 0 1 0 0 0 0 ...
 $ high_value_order     : chr  "True" "True" "False" "False" ...
'data.frame':	950 obs. of  16 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2026-04-28 05:59:54" "" "" "" ...
 $ delivery_status              : chr  "Failed" "Ontime" "Ontime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...
 $ delivery_duration_hours      : num  16291 NA NA NA NA ...
 $ failed_delivery_flag         : int  1 0 0 0 0 0 0 0 0 1 ...
 $ delayed_delivery_flag        : int  0 0 0 1 0 1 1 0 0 0 ...

In [ ]:
#---------------QUESTIONS WE WILL ANSWER--------------------------
# QUERY 1: Overall Delivery Status
# QUERY 2: Hub Performance Analysis
# QUERY 3: Driver Performance Analysis
# QUERY 4: Vehicle Performance Analysis
# QUERY 5: Complaint Analysis
# QUERY 6: Delivery vs Complaints Analysis
# QUERY 7: Incident Analysis
# QUERY 8: App Event Analysis
# QUERY 9: Hub Volume vs Complaints & Failures
# QUERY 10: Factors Linked to Poor Service

In [ ]:
#-------------QUERY 1: Overall Delivery Status---------------------
# 1. Count deliveries by delivery status
query1 <- sqldf("
SELECT
    delivery_status,
    COUNT(*) AS total_deliveries
FROM DELIVERY
GROUP BY delivery_status
ORDER BY total_deliveries DESC
")

# 2. Display query result
query1

  delivery_status total_deliveries
1 Ontime          616
2 Delayed         202
3 Failed          132

In [ ]:
#-------------QUERY 2: Hub Performance Analysis---------------------
# 1. Delivery performance by hub
query2 <- sqldf("
SELECT
    h.hub_name,
    h.zone,
    COUNT(d.delivery_id) AS total_deliveries,
    SUM(CASE WHEN d.delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed_deliveries,
    SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,
    ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_customer_rating

FROM DELIVERY d
JOIN HUB h
    ON d.hub_id = h.hub_id
GROUP BY h.hub_name, h.zone
ORDER BY delayed_deliveries DESC
")

# 2. Display query result
query2

  hub_name       zone      total_deliveries delayed_deliveries
1 West Gate      West      127              28
2 Airport Hub    Airport   104              27
3 North Exchange North     136              26
4 South Link     South     106              26
5 Central Core   Central   115              25
6 Riverside Hub  Riverside 115              25
7 East Dock      East      119              23
8 Midtown Relay  Central   128              22
  failed_deliveries avg_customer_rating
1 16                3.92
2 15                3.88
3 17                3.84
4 10                3.95
5 23                3.68
6 14                3.88
7 11                3.90
8 26                3.89

In [ ]:
#-------------QUERY 3: Driver Performance Analysis---------------------
# 1. Driver performance analysis
query3 <- sqldf("
SELECT
    dr.driver_id,
    dr.base_zone,
    dr.years_experience,
    dr.training_score,

    COUNT(de.delivery_id) AS total_deliveries,

    SUM(CASE WHEN de.delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed_deliveries,

    SUM(CASE WHEN de.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,

    ROUND(AVG(de.customer_rating_post_delivery), 2) AS avg_customer_rating

FROM DELIVERY de

JOIN DRIVER dr
    ON de.driver_id = dr.driver_id

GROUP BY dr.driver_id, dr.base_zone, dr.years_experience, dr.training_score

ORDER BY failed_deliveries DESC, delayed_deliveries DESC

LIMIT 10
")

# 2. Display query result
query3

   driver_id base_zone years_experience training_score total_deliveries
1  D133      South     12               88.2           12
2  D024      Riverside  8               71.4            8
3  D104      West      15               87.7            7
4  D055      Central   15               90.5           10
5  D131      South      9               86.7            9
6  D004      Airport   13               88.9            9
7  D083      North     12               80.8            9
8  D010      West       8               70.0            7
9  D092      East      15               88.2            5
10 D108      South     10               70.6           11
   delayed_deliveries failed_deliveries avg_customer_rating
1  2                  4                 3.42
2  0                  4                 3.44
3  0                  4                 3.93
4  2                  3                 3.81
5  2                  3                 3.66
6  1                  3                 3.51
7  1                  3                 3.91
8  0                  3                 4.15
9  0                  3                 3.38
10 0                  3                 4.41

In [ ]:
#-------------QUERY 4: Vehicle Performance Analysis---------------------
# 1. Vehicle performance analysis
query4 <- sqldf("
SELECT
    v.vehicle_type,
    v.maintenance_status,

    COUNT(d.delivery_id) AS total_deliveries,

    SUM(CASE WHEN d.delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed_deliveries,

    SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,

    ROUND(AVG(v.battery_health_pct), 2) AS avg_battery_health

FROM DELIVERY d

JOIN VEHICLE v
    ON d.vehicle_id = v.vehicle_id

GROUP BY v.vehicle_type, v.maintenance_status

ORDER BY failed_deliveries DESC
")

# 2. Display query result
query4

   vehicle_type maintenance_status total_deliveries delayed_deliveries
1  Cargovan     Inrepair            68              16
2  Hybrid       Inrepair            71              11
3  Diesel       Inrepair            55              11
4  Ev           Inrepair            60              14
5  Hybrid       Active             131              25
6  Cargovan     Active             117              29
7  Ev           Active             214              48
8  Diesel       Active              80              11
9  Cargovan     Scheduled           38               8
10 Ev           Scheduled           65              12
11 Hybrid       Scheduled           42              16
12 Diesel       Scheduled            9               1
   failed_deliveries avg_battery_health
1  22                69.82
2  21                83.27
3  17                75.65
4  17                77.79
5  15                74.30
6  11                74.41
7  11                82.86
8   8                67.02
9   5                68.96
10  2                82.92
11  2                80.56
12  1                81.33

In [ ]:
#-------------QUERY 5: Complaint Analysis---------------------
# 1. Complaint type and severity analysis
query5 <- sqldf("
SELECT
    complaint_type,
    severity,

    COUNT(*) AS total_complaints,

    ROUND(AVG(resolution_days), 2) AS avg_resolution_days,

    ROUND(AVG(compensation_amount), 2) AS avg_compensation

FROM COMPLAINT

GROUP BY complaint_type, severity

ORDER BY total_complaints DESC
")

# 2. Display query result
query5

   complaint_type    severity total_complaints avg_resolution_days
1  Delay             Medium   56                5.96
2  Missedpickup      Medium   37                6.16
3  Driverbehaviour   Medium   31                5.42
4  Delay             Low      27                6.48
5  Appissue          Medium   25                7.36
6  Delay             High     18               12.44
7  Driverbehaviour   High     16               13.75
8  Missedpickup      High     16               11.56
9  Appissue          Low      15                6.07
10 Appissue          High     13               13.92
11 Supportexperience Medium   12                6.17
12 Missedpickup      Low      11                6.91
13 Billing           Medium    9                5.78
14 Damage            High      7               15.43
15 Damage            Low       6                6.83
16 Supportexperience Low       5                6.20
17 Billing           High      4               12.00
18 Driverbehaviour   Low       4                7.00
19 Billing           Low       3                8.00
20 Supportexperience High      3               14.67
21 Damage            Medium    2               10.50
   avg_compensation
1  17.23
2  17.43
3  15.36
4   8.16
5  15.46
6  28.42
7  28.79
8  43.07
9  12.37
10 31.43
11 18.68
12  8.14
13 16.90
14 37.26
15 10.83
16  3.34
17 52.32
18  9.04
19  6.86
20 33.88
21 16.94

In [ ]:
#-------------QUERY 6: Delivery vs Complaints---------------------
# 1. Link delivery status with complaints
query6 <- sqldf("
SELECT
    de.delivery_status,
    COUNT(DISTINCT de.delivery_id) AS total_deliveries,
    COUNT(c.complaint_id) AS total_complaints,
    ROUND(AVG(c.resolution_days), 2) AS avg_resolution_days,
    ROUND(AVG(c.compensation_amount), 2) AS avg_compensation

FROM DELIVERY de

LEFT JOIN ORDER_DATA o
    ON de.order_id = o.order_id
LEFT JOIN COMPLAINT c
    ON o.order_id = c.order_id
GROUP BY de.delivery_status
ORDER BY total_complaints DESC
")

# 2. Display query result
query6

  delivery_status total_deliveries total_complaints avg_resolution_days
1 Ontime          616              149              7.60
2 Delayed         202               48              7.63
3 Failed          132               35              9.66
  avg_compensation
1 18.53
2 16.45
3 25.47

In [ ]:
#-------------QUERY 7: Incident Analysis---------------------
# 1. Incident analysis by delivery status
query7 <- sqldf("
SELECT
    de.delivery_status,
    i.incident_type,
    i.severity,

    COUNT(i.incident_id) AS total_incidents,

    ROUND(AVG(i.resolved_hours), 2) AS avg_resolution_hours

FROM DELIVERY de

JOIN INCIDENT i
    ON de.delivery_id = i.delivery_id

GROUP BY de.delivery_status, i.incident_type, i.severity

ORDER BY total_incidents DESC
")

# 2. Display query result
query7

   delivery_status incident_type    severity total_incidents
1  Ontime          Proofmissing     Medium   14
2  Ontime          Customernoshow   Low      13
3  Ontime          Routedeviation   Low      13
4  Ontime          Vehiclefault     Medium   12
5  Ontime          Batteryalert     Medium   10
6  Ontime          Temperatureissue Medium   10
7  Ontime          Proofmissing     Low       9
8  Ontime          Vehiclefault     High      9
9  Ontime          Appsyncerror     Low       8
10 Ontime          Customernoshow   Medium    8
11 Ontime          Routedeviation   High      8
12 Delayed         Appsyncerror     Medium    7
13 Ontime          Batteryalert     Low       7
14 Ontime          Routedeviation   Medium    7
15 Ontime          Appsyncerror     Medium    6
16 Ontime          Batteryalert     High      6
17 Ontime          Customernoshow   High      6
18 Ontime          Vehiclefault     Low       6
19 Delayed         Customernoshow   Medium    5
20 Ontime          Proofmissing     High      5
21 Ontime          Safetynearmiss   Medium    5
22 Delayed         Batteryalert     Medium    4
23 Failed          Batteryalert     Medium    4
24 Failed          Proofmissing     High      4
25 Ontime          Customernoshow   Critical  4
26 Ontime          Temperatureissue Low       4
27 Delayed         Proofmissing     Critical  3
28 Delayed         Proofmissing     High      3
29 Delayed         Routedeviation   High      3
30 Delayed         Routedeviation   Medium    3
⋮  ⋮               ⋮                ⋮        ⋮
43 Delayed         Vehiclefault     Medium   2
44 Failed          Appsyncerror     High     2
45 Failed          Appsyncerror     Medium   2
46 Failed          Proofmissing     Low      2
47 Failed          Routedeviation   Low      2
48 Failed          Safetynearmiss   High     2
49 Failed          Temperatureissue Critical 2
50 Failed          Temperatureissue High     2
51 Failed          Temperatureissue Low      2
52 Failed          Vehiclefault     Medium   2
53 Ontime          Appsyncerror     High     2
54 Ontime          Batteryalert     Critical 2
55 Ontime          Vehiclefault     Critical 2
56 Delayed         Batteryalert     High     1
57 Delayed         Batteryalert     Low      1
58 Delayed         Customernoshow   Critical 1
59 Delayed         Proofmissing     Medium   1
60 Delayed         Safetynearmiss   High     1
61 Delayed         Safetynearmiss   Medium   1
62 Delayed         Vehiclefault     Critical 1
63 Delayed         Vehiclefault     High     1
64 Delayed         Vehiclefault     Low      1
65 Failed          Appsyncerror     Low      1
66 Failed          Batteryalert     High     1
67 Failed          Routedeviation   Critical 1
68 Failed          Routedeviation   High     1
69 Failed          Vehiclefault     Low      1
70 Ontime          Appsyncerror     Critical 1
71 Ontime          Safetynearmiss   Critical 1
72 Ontime          Safetynearmiss   High     1
   avg_resolution_hours
1  11.11
2  14.35
3  15.48
4   4.75
5  11.02
6  15.28
7  14.34
8  13.46
9  14.67
10 14.46
11 14.89
12 11.97
13  8.37
14  9.67
15 10.98
16 16.22
17 11.28
18  8.83
19 13.42
20  8.10
21 12.48
22 10.50
23 12.15
24  4.00
25 11.70
26 14.38
27  8.20
28  4.50
29 11.47
30 11.67
⋮  ⋮
43  7.35
44 11.00
45 14.05
46 14.40
47 14.65
48  8.25
49  4.10
50 10.70
51 17.25
52 10.85
53 12.00
54 12.80
55  8.50
56 17.30
57 10.20
58 10.20
59 11.40
60  6.50
61 17.30
62 26.70
63  9.10
64  6.10
65 20.10
66 11.30
67 18.10
68  3.20
69 14.50
70 10.30
71 12.10
72  0.40

In [ ]:
#-------------QUERY 8: App Event Analysis---------------------
# 1. App event success and failure analysis
query8 <- sqldf("
SELECT
    event_type,

    COUNT(*) AS total_events,

    SUM(CASE WHEN success_flag = 1 THEN 1 ELSE 0 END) AS successful_events,

    SUM(CASE WHEN success_flag = 0 THEN 1 ELSE 0 END) AS failed_events,

    ROUND(AVG(api_latency_ms), 2) AS avg_api_latency

FROM APP_EVENT

GROUP BY event_type

ORDER BY failed_events DESC
")

# 2. Display query result
query8

  event_type                  total_events successful_events failed_events
1 payment_retry                69           50               19
2 chat_escalated               38           19               19
3 track_order                 138          138                0
4 search_route                 99           99                0
5 eta_refresh                 105          105                0
6 delivery_instruction_update  75           75                0
7 chat_opened                  88           88                0
8 cancel_attempt               28           28                0
  avg_api_latency
1 472.68
2 478.13
3 460.71
4 456.51
5 452.15
6 496.29
7 478.33
8 417.14

In [ ]:
#-------------QUERY 9: Hub Volume vs Complaints & Failures---------------------
# 1. Analyse hub performance with complaints and failures
query9 <- sqldf("
SELECT
    h.hub_name,
    h.zone,
    COUNT(d.delivery_id) AS total_deliveries,
    SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,
    SUM(CASE WHEN d.delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed_deliveries,
    COUNT(c.complaint_id) AS total_complaints

FROM HUB h

LEFT JOIN DELIVERY d
    ON h.hub_id = d.hub_id
LEFT JOIN ORDER_DATA o
    ON d.order_id = o.order_id
LEFT JOIN COMPLAINT c
    ON o.order_id = c.order_id
GROUP BY h.hub_name, h.zone
ORDER BY total_deliveries DESC
")

# 2. Display result
query9

  hub_name       zone      total_deliveries failed_deliveries
1 North Exchange North     142              18
2 Midtown Relay  Central   132              27
3 West Gate      West      129              16
4 East Dock      East      121              11
5 Riverside Hub  Riverside 118              14
6 Central Core   Central   117              23
7 South Link     South     108              10
8 Airport Hub    Airport   106              15
  delayed_deliveries total_complaints
1 26                 32
2 23                 35
3 29                 28
4 23                 33
5 25                 33
6 25                 30
7 27                 18
8 27                 23

In [ ]:
#-------------QUERY 10: Factors Linked to Poor Service---------------------
# 1. Combine multiple factors affecting delivery performance
query10 <- sqldf("
SELECT
    d.delivery_status,
    dr.base_zone,
    dr.training_score,
    v.vehicle_type,
    v.maintenance_status,
    i.incident_type,
    i.severity,

    COUNT(d.delivery_id) AS total_cases,

    ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_rating

FROM DELIVERY d

LEFT JOIN DRIVER dr
    ON d.driver_id = dr.driver_id

LEFT JOIN VEHICLE v
    ON d.vehicle_id = v.vehicle_id

LEFT JOIN INCIDENT i
    ON d.delivery_id = i.delivery_id

GROUP BY
    d.delivery_status,
    dr.base_zone,
    dr.training_score,
    v.vehicle_type,
    v.maintenance_status,
    i.incident_type,
    i.severity

ORDER BY total_cases DESC
")

# 2. Display result
query10

    delivery_status base_zone training_score vehicle_type maintenance_status
1   Ontime          Central   69.5           Ev           Active
2   Ontime          Central   76.1           Ev           Active
3   Ontime          North     59.6           Hybrid       Active
4   Ontime          North     90.5           Ev           Active
5   Ontime          South     64.6           Diesel       Active
6   Ontime          South     74.1           Ev           Active
7   Ontime          South     75.2           Cargovan     Active
8   Ontime          South     84.1           Ev           Active
9   Ontime          West      74.6           Ev           Active
10  Ontime          West      85.0           Ev           Active
11  Delayed         Airport   98.7           Ev           Active
12  Delayed         Central   79.5           Hybrid       Active
13  Delayed         North     70.6           Hybrid       Inrepair
14  Delayed         North     93.6           Hybrid       Scheduled
15  Delayed         South     75.2           Ev           Active
16  Failed          Airport   79.3           Ev           Active
17  Failed          East      88.2           Cargovan     Inrepair
18  Failed          North     82.2           Cargovan     Inrepair
19  Failed          Riverside 71.4           Diesel       Inrepair
20  Failed          Riverside 71.4           Hybrid       Active
21  Failed          South     70.6           Cargovan     Inrepair
22  Failed          South     86.7           Cargovan     Inrepair
23  Failed          South     88.2           Ev           Inrepair
24  Failed          West      87.7           Hybrid       Active
25  Failed          West      99.0           Ev           Inrepair
26  Ontime          Airport   63.4           Ev           Active
27  Ontime          Airport   79.3           Diesel       Active
28  Ontime          Airport   79.3           Ev           Active
29  Ontime          Airport   86.1           Ev           Active
30  Ontime          Airport   86.1           Hybrid       Active
⋮   ⋮               ⋮         ⋮              ⋮            ⋮
855 Ontime          West      74.6           Cargovan     Active
856 Ontime          West      74.6           Cargovan     Active
857 Ontime          West      74.6           Ev           Scheduled
858 Ontime          West      74.6           Hybrid       Scheduled
859 Ontime          West      75.0           Cargovan     Active
860 Ontime          West      75.0           Ev           Active
861 Ontime          West      75.0           Hybrid       Active
862 Ontime          West      75.0           Hybrid       Scheduled
863 Ontime          West      75.2           Diesel       Active
864 Ontime          West      75.6           Diesel       Inrepair
865 Ontime          West      77.0           Cargovan     Active
866 Ontime          West      77.0           Ev           Active
867 Ontime          West      77.0           Hybrid       Inrepair
868 Ontime          West      79.1           Cargovan     Active
869 Ontime          West      79.1           Cargovan     Inrepair
870 Ontime          West      79.1           Ev           Scheduled
871 Ontime          West      80.1           Cargovan     Active
872 Ontime          West      80.1           Cargovan     Active
873 Ontime          West      80.1           Diesel       Inrepair
874 Ontime          West      80.1           Ev           Active
875 Ontime          West      80.1           Hybrid       Active
876 Ontime          West      80.8           Ev           Scheduled
877 Ontime          West      83.3           Cargovan     Inrepair
878 Ontime          West      83.3           Cargovan     Inrepair
879 Ontime          West      83.3           Hybrid       Active
880 Ontime          West      87.7           Diesel       Inrepair
881 Ontime          West      87.7           Ev           Scheduled
882 Ontime          West      87.7           Hybrid       Scheduled
883 Ontime          West      99.0           Ev           Inrepair
884 Ontime          West      99.0           Hybrid       Active
    incident_type    severity total_cases avg_rating
1   NA               NA       3           4.14
2   NA               NA       3           4.80
3   NA               NA       3           4.50
4   NA               NA       3           4.15
5   NA               NA       3           4.45
6   NA               NA       3           4.52
7   NA               NA       3           4.26
8   NA               NA       3           4.00
9   NA               NA       3           3.84
10  NA               NA       3           4.17
11  NA               NA       2           3.86
12  NA               NA       2           3.33
13  NA               NA       2           3.17
14  Customernoshow   Medium   2           2.52
15  NA               NA       2           2.90
16  NA               NA       2           3.64
17  NA               NA       2           3.42
18  NA               NA       2           1.94
19  NA               NA       2           2.27
20  NA               NA       2           2.88
21  NA               NA       2           3.61
22  NA               NA       2           3.26
23  NA               NA       2           2.67
24  NA               NA       2           3.10
25  NA               NA       2           2.64
26  NA               NA       2           4.73
27  NA               NA       2           4.58
28  NA               NA       2           5.00
29  Routedeviation   Low      2           3.74
30  NA               NA       2           4.46
⋮   ⋮                ⋮        ⋮           ⋮
855 Proofmissing     Low      1           4.15
856 Routedeviation   Low      1           4.04
857 Batteryalert     Low      1           3.98
858 Batteryalert     Low      1           4.42
859 NA               NA       1           4.31
860 Customernoshow   Medium   1           3.96
861 NA               NA       1           4.04
862 Batteryalert     Critical 1           4.15
863 NA               NA       1           4.06
864 Routedeviation   Low      1           4.65
865 NA               NA       1           4.47
866 Temperatureissue Low      1           4.95
867 NA               NA       1           4.01
868 Vehiclefault     Medium   1           4.26
869 NA               NA       1           3.93
870 NA               NA       1           4.21
871 Proofmissing     Medium   1           4.08
872 Temperatureissue Critical 1           3.50
873 NA               NA       1           4.26
874 Customernoshow   Medium   1           3.89
875 NA               NA       1           4.38
876 NA               NA       1           4.61
877 Customernoshow   Low      1           4.09
878 Routedeviation   High     1           4.09
879 NA               NA       1           4.45
880 NA               NA       1           4.99
881 NA               NA       1           4.86
882 NA               NA       1           4.03
883 Safetynearmiss   Medium   1           4.64
884 NA               NA       1           4.11