<a href="https://colab.research.google.com/github/Mohommad-Nuzlan-GH/M-R-M-Nuzlan-Database-Analytics-Top-Up-2026/blob/main/5_MongoDB_Development_NS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#1 -  Install MongoDB Python driver

!pip install "pymongo[srv]"

Collecting pymongo[srv]
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
WARNING: pymongo 4.17.0 does not provide the extra 'srv'
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo[srv])
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 6.8 MB/s eta 0:00:00
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 44.0 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [7]:
#2 -  import required libraries
import pandas as pd
import numpy as np
from pymongo import MongoClient
from getpass import getpass
from urllib.parse import quote_plus
import certifi
from pprint import pprint

In [8]:
#3 -  Connect Google Colab to MongoDB Atlas

from pymongo import MongoClient

connection_string = "mongodb+srv://northstar_user:MongoDBNS2026@northstarcluster.dvhx1t0.mongodb.net/?appName=NorthStarCluster"

client = MongoClient(connection_string)

# Test connection
client.admin.command('ping')

print("MongoDB Atlas connection successful!")

MongoDB Atlas connection successful!

In [9]:
#4 - Create MongoDB database and collections

# Create / select database
db = client["NorthStar_Mobility_DB"]

# Define collection names based on the NoSQL design
collection_names = [
    "delivery_cases",
    "customers",
    "hubs",
    "app_events"
]

# Create collections if they do not already exist
existing_collections = db.list_collection_names()

for collection in collection_names:
    if collection not in existing_collections:
        db.create_collection(collection)
        print(f"Collection created: {collection}")
    else:
        print(f"Collection already exists: {collection}")

# Display all collections in the database
print("\nCollections in NorthStar_Mobility_DB:")
print(db.list_collection_names())

Collection already exists: delivery_cases
Collection already exists: customers
Collection already exists: hubs
Collection already exists: app_events

Collections in NorthStar_Mobility_DB:
['customers', 'delivery_cases', 'hubs', 'app_events']

In [10]:
#5 - Create MongoDB collection variables

delivery_cases_col = db["delivery_cases"]
customers_col = db["customers"]
hubs_col = db["hubs"]
app_events_col = db["app_events"]

print("MongoDB collection variables created successfully.")
print("Database:", db.name)
print("Collections:", db.list_collection_names())

MongoDB collection variables created successfully.
Database: NorthStar_Mobility_DB
Collections: ['customers', 'delivery_cases', 'hubs', 'app_events']

In [11]:
#6 - Upload cleaned CSV files into Google Colab

from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for file_name in uploaded.keys():
    print(file_name)

Saving 2#clean_app_events.csv to 2#clean_app_events.csv
Saving 1#clean_customers.csv to 1#clean_customers.csv
Saving 3#clean_orders.csv to 3#clean_orders.csv
Saving 4#clean_complaints.csv to 4#clean_complaints.csv
Saving 5#clean_deliveries.csv to 5#clean_deliveries.csv
Saving 6#clean_drivers.csv to 6#clean_drivers.csv
Saving 7#clean_vehicles.csv to 7#clean_vehicles.csv
Saving 8#clean_hubs.csv to 8#clean_hubs.csv
Saving 9#clean_incidents.csv to 9#clean_incidents.csv
Uploaded files:
2#clean_app_events.csv
1#clean_customers.csv
3#clean_orders.csv
4#clean_complaints.csv
5#clean_deliveries.csv
6#clean_drivers.csv
7#clean_vehicles.csv
8#clean_hubs.csv
9#clean_incidents.csv

In [12]:
#7 - Load cleaned datasets

CUSTOMER = pd.read_csv("1#clean_customers.csv")
APP_EVENT = pd.read_csv("2#clean_app_events.csv")
ORDER = pd.read_csv("3#clean_orders.csv")
COMPLAINT = pd.read_csv("4#clean_complaints.csv")
DELIVERY = pd.read_csv("5#clean_deliveries.csv")
DRIVER = pd.read_csv("6#clean_drivers.csv")
VEHICLE = pd.read_csv("7#clean_vehicles.csv")
HUB = pd.read_csv("8#clean_hubs.csv")
INCIDENT = pd.read_csv("9#clean_incidents.csv")

datasets = {
    "CUSTOMER": CUSTOMER,
    "APP_EVENT": APP_EVENT,
    "ORDER": ORDER,
    "COMPLAINT": COMPLAINT,
    "DELIVERY": DELIVERY,
    "DRIVER": DRIVER,
    "VEHICLE": VEHICLE,
    "HUB": HUB,
    "INCIDENT": INCIDENT
}

for name, df in datasets.items():
    print(name, "shape:", df.shape)

CUSTOMER shape: (650, 10)
APP_EVENT shape: (640, 12)
ORDER shape: (1250, 12)
COMPLAINT shape: (320, 11)
DELIVERY shape: (950, 16)
DRIVER shape: (170, 9)
VEHICLE shape: (120, 9)
HUB shape: (8, 6)
INCIDENT shape: (280, 8)

In [13]:
 #8 - Convert date columns into datetime format

date_columns = {
    "CUSTOMER": ["signup_date"],
    "APP_EVENT": ["event_timestamp"],
    "ORDER": ["order_created_at"],
    "COMPLAINT": ["created_at"],
    "DELIVERY": ["dispatch_time", "delivery_completed_at"],
    "VEHICLE": ["commission_date"],
    "INCIDENT": ["reported_at"]
}

for dataset_name, columns in date_columns.items():
    df = datasets[dataset_name]
    for col in columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

print("Date conversion completed.")

Date conversion completed.

/tmp/ipykernel_503/3663818083.py:17: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

In [14]:
#9 - Helper functions for MongoDB document conversion

def convert_value(value):
    """
    Converts Pandas/Numpy values into MongoDB-safe Python values.
    """
    if pd.isna(value):
        return None

    if isinstance(value, pd.Timestamp):
        return value.to_pydatetime()

    if isinstance(value, np.integer):
        return int(value)

    if isinstance(value, np.floating):
        return float(value)

    if isinstance(value, np.bool_):
        return bool(value)

    return value


def row_to_dict(row):
    """
    Converts a Pandas row into a clean dictionary for MongoDB.
    """
    return {col: convert_value(row[col]) for col in row.index}


def dataframe_to_lookup(df, key_col):
    """
    Converts dataframe into dictionary lookup using a key column.
    """
    lookup = {}
    for _, row in df.iterrows():
        key = row.get(key_col)
        if pd.notna(key):
            lookup[str(key)] = row_to_dict(row)
    return lookup


def related_records(df, key_col, key_value):
    """
    Returns all records from a dataframe matching a key value.
    """
    if key_value is None:
        return []

    matched_df = df[df[key_col].astype(str) == str(key_value)]
    return [row_to_dict(row) for _, row in matched_df.iterrows()]

In [15]:
#10 - Create lookup dictionaries

order_lookup = dataframe_to_lookup(ORDER, "order_id")
customer_lookup = dataframe_to_lookup(CUSTOMER, "customer_id")
driver_lookup = dataframe_to_lookup(DRIVER, "driver_id")
vehicle_lookup = dataframe_to_lookup(VEHICLE, "vehicle_id")
hub_lookup = dataframe_to_lookup(HUB, "hub_id")

print("Lookup dictionaries created:")
print("Orders:", len(order_lookup))
print("Customers:", len(customer_lookup))
print("Drivers:", len(driver_lookup))
print("Vehicles:", len(vehicle_lookup))
print("Hubs:", len(hub_lookup))

Lookup dictionaries created:
Orders: 1250
Customers: 650
Drivers: 170
Vehicles: 120
Hubs: 8

In [16]:
#11 - Build nested delivery_cases documents
delivery_case_documents = []

for _, delivery_row in DELIVERY.iterrows():
    delivery_doc = row_to_dict(delivery_row)

    delivery_id = str(delivery_doc.get("delivery_id"))
    order_id = delivery_doc.get("order_id")
    driver_id = delivery_doc.get("driver_id")
    vehicle_id = delivery_doc.get("vehicle_id")
    hub_id = delivery_doc.get("hub_id")
    order_doc = order_lookup.get(str(order_id), {})
    customer_id = order_doc.get("customer_id")

    customer_doc = customer_lookup.get(str(customer_id), {})
    driver_doc = driver_lookup.get(str(driver_id), {})
    vehicle_doc = vehicle_lookup.get(str(vehicle_id), {})
    hub_doc = hub_lookup.get(str(hub_id), {})

    incident_docs = related_records(INCIDENT, "delivery_id", delivery_id)
    complaint_docs = related_records(COMPLAINT, "order_id", order_id)
    app_event_docs = related_records(APP_EVENT, "order_id", order_id)

    case_document = {
        "_id": delivery_id,
        "delivery_id": delivery_id,
        "delivery_status": delivery_doc.get("delivery_status"),
        "dispatch_time": delivery_doc.get("dispatch_time"),
        "delivery_completed_at": delivery_doc.get("delivery_completed_at"),
        "delivery_duration_hours": delivery_doc.get("delivery_duration_hours"),
        "customer_rating_post_delivery": delivery_doc.get("customer_rating_post_delivery"),
        "failed_delivery_flag": delivery_doc.get("failed_delivery_flag"),
        "delayed_delivery_flag": delivery_doc.get("delayed_delivery_flag"),

        "delivery": delivery_doc,
        "order": order_doc,
        "customer": customer_doc,
        "driver": driver_doc,
        "vehicle": vehicle_doc,
        "hub": hub_doc,

        "incidents": incident_docs,
        "complaints": complaint_docs,
        "app_events": app_event_docs,

        "case_summary": {
            "has_incident": len(incident_docs) > 0,
            "has_complaint": len(complaint_docs) > 0,
            "has_app_events": len(app_event_docs) > 0,
            "incident_count": len(incident_docs),
            "complaint_count": len(complaint_docs),
            "app_event_count": len(app_event_docs)
        }
    }
    delivery_case_documents.append(case_document)

print("Nested delivery case documents created:", len(delivery_case_documents))
# Show one sample nested document
pprint(delivery_case_documents[0])

Nested delivery case documents created: 950
{'_id': 'DL00001',
 'app_events': [],
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'complaints': [],
 'customer': {'account_status': 'Active',
              'age': 74,
              'age_group': 'Senior',
              'app_engagement_score': 64.9,
              'customer_id': 'C0567',
              'customer_type': 'Consumer',
              'home_zone': 'East',
              'loyalty_score': 79.7,
              'preferred_channel': 'App',
              'signup_date': datetime.datetime(2024, 2, 18, 4, 31)},
 'customer_rating_post_delivery': 3.07,
 'delayed_delivery_flag': 0,
 'delivery': {'customer_rating_post_delivery': 3.07,
              'delayed_delivery_flag': 0,
              'delivery_completed_at': datetime.datetime(2026, 4, 28, 5, 59, 54),
              'delivery_duration_hours': 16291.048333333334,
              'delivery_id': 'DL00001',
              'delivery_status': 'Failed',
              'dispatch_time': datetime.datetime(2024, 6, 18, 10, 57),
              'driver_id': 'D004',
              'failed_delivery_flag': 1,
              'fuel_or_charge_cost': 12.05,
              'hub_id': 'H05',
              'manual_route_override_count': 1,
              'order_id': 'O00938',
              'proof_of_completion_missing': 0,
              'route_distance_km': 17.26,
              'vehicle_id': 'V056'},
 'delivery_completed_at': datetime.datetime(2026, 4, 28, 5, 59, 54),
 'delivery_duration_hours': 16291.048333333334,
 'delivery_id': 'DL00001',
 'delivery_status': 'Failed',
 'dispatch_time': datetime.datetime(2024, 6, 18, 10, 57),
 'driver': {'active_flag': 1,
            'base_zone': 'Airport',
            'driver_id': 'D004',
            'driver_rating': 4.75,
            'employment_type': 'Parttime',
            'experience_level': 'Senior',
            'shift_preference': 'Morning',
            'training_score': 88.9,
            'years_experience': 13},
 'failed_delivery_flag': 1,
 'hub': {'capacity_category': 'High',
         'capacity_score': 88,
         'hub_id': 'H05',
         'hub_name': 'Central Core',
         'hub_type': 'Control',
         'zone': 'Central'},
 'incidents': [{'delivery_id': 'DL00001',
                'incident_id': 'I0180',
                'incident_type': 'Proofmissing',
                'reported_at': None,
                'resolution_status': 'Open',
                'resolved_hours': 5.6,
                'severity': 'High',
                'unresolved_flag': 1}],
 'order': {'booking_channel': 'Web',
           'customer_id': 'C0567',
           'dropoff_zone': 'Central',
           'high_value_order': True,
           'order_created_at': datetime.datetime(2024, 6, 18, 9, 48),
           'order_id': 'O00938',
           'order_value': 151.14,
           'pickup_zone': 'Central',
           'priority_level': 'Medium',
           'promised_window_hours': 6,
           'service_type': 'Business',
           'special_handling_flag': 0},
 'vehicle': {'assigned_zone': 'Central',
             'battery_health_category': 'Medium',
             'battery_health_pct': 78.4,
             'commission_date': datetime.datetime(2024, 6, 9, 16, 18),
             'maintenance_status': 'Active',
             'odometer_km': 29849,
             'telematics_version': 'v2.2',
             'vehicle_id': 'V056',
             'vehicle_type': 'Ev'}}

In [17]:
#12 - Build customer documents

customer_documents = []

for _, customer_row in CUSTOMER.iterrows():
    customer_doc = row_to_dict(customer_row)
    customer_id = customer_doc.get("customer_id")

    customer_orders = ORDER[ORDER["customer_id"].astype(str) == str(customer_id)]
    customer_complaints = COMPLAINT[COMPLAINT["customer_id"].astype(str) == str(customer_id)]
    customer_app_events = APP_EVENT[APP_EVENT["customer_id"].astype(str) == str(customer_id)]

    document = {
        "_id": str(customer_id),
        "customer_id": customer_id,
        "profile": customer_doc,
        "service_summary": {
            "total_orders": int(customer_orders["order_id"].nunique()) if "order_id" in customer_orders.columns else 0,
            "total_complaints": int(customer_complaints["complaint_id"].nunique()) if "complaint_id" in customer_complaints.columns else 0,
            "total_app_events": int(customer_app_events["event_id"].nunique()) if "event_id" in customer_app_events.columns else 0
        }
    }

    customer_documents.append(document)

print("Customer documents created:", len(customer_documents))
pprint(customer_documents[0])

Customer documents created: 650
{'_id': 'C0001',
 'customer_id': 'C0001',
 'profile': {'account_status': 'Active',
             'age': 26,
             'age_group': 'Adult',
             'app_engagement_score': 69.2,
             'customer_id': 'C0001',
             'customer_type': 'Sme',
             'home_zone': 'North',
             'loyalty_score': 44.9,
             'preferred_channel': 'App',
             'signup_date': datetime.datetime(2024, 11, 27, 4, 25)},
 'service_summary': {'total_app_events': 0,
                     'total_complaints': 2,
                     'total_orders': 3}}

In [18]:
#13 - Build hub documents

hub_documents = []

for _, hub_row in HUB.iterrows():
    hub_doc = row_to_dict(hub_row)
    hub_id = hub_doc.get("hub_id")

    hub_deliveries = DELIVERY[DELIVERY["hub_id"].astype(str) == str(hub_id)]

    total_deliveries = len(hub_deliveries)
    failed_deliveries = int((hub_deliveries["delivery_status"] == "Failed").sum())
    delayed_deliveries = int((hub_deliveries["delivery_status"] == "Delayed").sum())

    if total_deliveries > 0:
        failure_rate = round(100 * failed_deliveries / total_deliveries, 2)
        delay_rate = round(100 * delayed_deliveries / total_deliveries, 2)
    else:
        failure_rate = 0
        delay_rate = 0

    document = {
        "_id": str(hub_id),
        "hub_id": hub_id,
        "hub_profile": hub_doc,
        "performance_summary": {
            "total_deliveries": total_deliveries,
            "failed_deliveries": failed_deliveries,
            "delayed_deliveries": delayed_deliveries,
            "failure_rate": failure_rate,
            "delay_rate": delay_rate
        }
    }

    hub_documents.append(document)

print("Hub documents created:", len(hub_documents))
pprint(hub_documents[0])

Hub documents created: 8
{'_id': 'H01',
 'hub_id': 'H01',
 'hub_profile': {'capacity_category': 'High',
                 'capacity_score': 82,
                 'hub_id': 'H01',
                 'hub_name': 'North Exchange',
                 'hub_type': 'Dispatch',
                 'zone': 'North'},
 'performance_summary': {'delay_rate': 19.12,
                         'delayed_deliveries': 26,
                         'failed_deliveries': 17,
                         'failure_rate': 12.5,
                         'total_deliveries': 136}}

In [19]:
#14 - Build app event documents

app_event_documents = []

for _, app_row in APP_EVENT.iterrows():
    app_doc = row_to_dict(app_row)
    event_id = app_doc.get("event_id")

    document = {
        "_id": str(event_id),
        "event_id": event_id,
        "event_details": app_doc
    }

    app_event_documents.append(document)

print("App event documents created:", len(app_event_documents))
pprint(app_event_documents[0])

App event documents created: 640
{'_id': 'AE00001',
 'event_details': {'api_latency_ms': 301,
                   'customer_id': 'C0488',
                   'device_type': 'Android',
                   'event_id': 'AE00001',
                   'event_success_status': 'Success',
                   'event_timestamp': datetime.datetime(2024, 8, 9, 3, 25),
                   'event_type': 'eta_refresh',
                   'latency_category': 'High',
                   'order_id': 'No_Order_Link',
                   'session_id': 'S19847',
                   'success_flag': 1,
                   'zone_context': 'North'},
 'event_id': 'AE00001'}

In [20]:
#15 - Clear existing documents before fresh insert

delivery_cases_col.delete_many({})
customers_col.delete_many({})
hubs_col.delete_many({})
app_events_col.delete_many({})

print("Existing documents cleared from MongoDB collections.")

Existing documents cleared from MongoDB collections.

In [21]:
#16 - Insert documents into MongoDB Atlas

if delivery_case_documents:
    result_delivery = delivery_cases_col.insert_many(delivery_case_documents)
    print("Inserted delivery_cases:", len(result_delivery.inserted_ids))

if customer_documents:
    result_customers = customers_col.insert_many(customer_documents)
    print("Inserted customers:", len(result_customers.inserted_ids))

if hub_documents:
    result_hubs = hubs_col.insert_many(hub_documents)
    print("Inserted hubs:", len(result_hubs.inserted_ids))

if app_event_documents:
    result_app_events = app_events_col.insert_many(app_event_documents)
    print("Inserted app_events:", len(result_app_events.inserted_ids))

Inserted delivery_cases: 950
Inserted customers: 650
Inserted hubs: 8
Inserted app_events: 640

In [22]:
#17 - Validate inserted collection counts

print("MongoDB collection counts:")

print("delivery_cases:", delivery_cases_col.count_documents({}))
print("customers:", customers_col.count_documents({}))
print("hubs:", hubs_col.count_documents({}))
print("app_events:", app_events_col.count_documents({}))

print("\nCollections in database:")
print(db.list_collection_names())

MongoDB collection counts:
delivery_cases: 950
customers: 650
hubs: 8
app_events: 640

Collections in database:
['customers', 'delivery_cases', 'hubs', 'app_events']

In [23]:
#18 - View one nested delivery case document

sample_case = delivery_cases_col.find_one()

pprint(sample_case)

{'_id': 'DL00001',
 'app_events': [],
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'complaints': [],
 'customer': {'account_status': 'Active',
              'age': 74,
              'age_group': 'Senior',
              'app_engagement_score': 64.9,
              'customer_id': 'C0567',
              'customer_type': 'Consumer',
              'home_zone': 'East',
              'loyalty_score': 79.7,
              'preferred_channel': 'App',
              'signup_date': datetime.datetime(2024, 2, 18, 4, 31)},
 'customer_rating_post_delivery': 3.07,
 'delayed_delivery_flag': 0,
 'delivery': {'customer_rating_post_delivery': 3.07,
              'delayed_delivery_flag': 0,
              'delivery_completed_at': datetime.datetime(2026, 4, 28, 5, 59, 54),
              'delivery_duration_hours': 16291.048333333334,
              'delivery_id': 'DL00001',
              'delivery_status': 'Failed',
              'dispatch_time': datetime.datetime(2024, 6, 18, 10, 57),
              'driver_id': 'D004',
              'failed_delivery_flag': 1,
              'fuel_or_charge_cost': 12.05,
              'hub_id': 'H05',
              'manual_route_override_count': 1,
              'order_id': 'O00938',
              'proof_of_completion_missing': 0,
              'route_distance_km': 17.26,
              'vehicle_id': 'V056'},
 'delivery_completed_at': datetime.datetime(2026, 4, 28, 5, 59, 54),
 'delivery_duration_hours': 16291.048333333334,
 'delivery_id': 'DL00001',
 'delivery_status': 'Failed',
 'dispatch_time': datetime.datetime(2024, 6, 18, 10, 57),
 'driver': {'active_flag': 1,
            'base_zone': 'Airport',
            'driver_id': 'D004',
            'driver_rating': 4.75,
            'employment_type': 'Parttime',
            'experience_level': 'Senior',
            'shift_preference': 'Morning',
            'training_score': 88.9,
            'years_experience': 13},
 'failed_delivery_flag': 1,
 'hub': {'capacity_category': 'High',
         'capacity_score': 88,
         'hub_id': 'H05',
         'hub_name': 'Central Core',
         'hub_type': 'Control',
         'zone': 'Central'},
 'incidents': [{'delivery_id': 'DL00001',
                'incident_id': 'I0180',
                'incident_type': 'Proofmissing',
                'reported_at': None,
                'resolution_status': 'Open',
                'resolved_hours': 5.6,
                'severity': 'High',
                'unresolved_flag': 1}],
 'order': {'booking_channel': 'Web',
           'customer_id': 'C0567',
           'dropoff_zone': 'Central',
           'high_value_order': True,
           'order_created_at': datetime.datetime(2024, 6, 18, 9, 48),
           'order_id': 'O00938',
           'order_value': 151.14,
           'pickup_zone': 'Central',
           'priority_level': 'Medium',
           'promised_window_hours': 6,
           'service_type': 'Business',
           'special_handling_flag': 0},
 'vehicle': {'assigned_zone': 'Central',
             'battery_health_category': 'Medium',
             'battery_health_pct': 78.4,
             'commission_date': datetime.datetime(2024, 6, 9, 16, 18),
             'maintenance_status': 'Active',
             'odometer_km': 29849,
             'telematics_version': 'v2.2',
             'vehicle_id': 'V056',
             'vehicle_type': 'Ev'}}

In [24]:
#19 - CRUD -> "CREATE" operation

test_document = {
    "_id": "TEST_CASE_001",
    "delivery_id": "TEST_CASE_001",
    "delivery_status": "Delayed",
    "delivery": {
        "delivery_id": "TEST_CASE_001",
        "delivery_status": "Delayed",
        "dispatch_time": None,
        "delivery_completed_at": None
    },
    "order": {
        "order_id": "TEST_ORDER_001",
        "service_type": "Test Service",
        "priority_level": "High"
    },
    "customer": {
        "customer_id": "TEST_CUSTOMER_001",
        "customer_type": "Consumer"
    },
    "hub": {
        "hub_name": "Test Hub",
        "zone": "Central"
    },
    "incidents": [],
    "complaints": [],
    "app_events": [],
    "case_summary": {
        "has_incident": False,
        "has_complaint": False,
        "has_app_events": False,
        "incident_count": 0,
        "complaint_count": 0,
        "app_event_count": 0
    }
}

create_result = delivery_cases_col.insert_one(test_document)

print("Created document ID:", create_result.inserted_id)

Created document ID: TEST_CASE_001

In [25]:
#20 - CRUD-> "READ" operation

read_result = delivery_cases_col.find_one({"_id": "TEST_CASE_001"})

pprint(read_result)

{'_id': 'TEST_CASE_001',
 'app_events': [],
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'complaints': [],
 'customer': {'customer_id': 'TEST_CUSTOMER_001', 'customer_type': 'Consumer'},
 'delivery': {'delivery_completed_at': None,
              'delivery_id': 'TEST_CASE_001',
              'delivery_status': 'Delayed',
              'dispatch_time': None},
 'delivery_id': 'TEST_CASE_001',
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Test Hub', 'zone': 'Central'},
 'incidents': [],
 'order': {'order_id': 'TEST_ORDER_001',
           'priority_level': 'High',
           'service_type': 'Test Service'}}

In [26]:
#21 - CRUD-> "UPDATE" operation

update_result = delivery_cases_col.update_one(
    {"_id": "TEST_CASE_001"},
    {
        "$set": {
            "delivery_status": "Resolved",
            "case_summary.reviewed_by": "Operations Team",
            "case_summary.review_note": "Test case updated successfully during MongoDB CRUD demonstration."
        }
    }
)

print("Matched documents:", update_result.matched_count)
print("Modified documents:", update_result.modified_count)

updated_document = delivery_cases_col.find_one({"_id": "TEST_CASE_001"})
pprint(updated_document)

Matched documents: 1
Modified documents: 1
{'_id': 'TEST_CASE_001',
 'app_events': [],
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0,
                  'review_note': 'Test case updated successfully during '
                                 'MongoDB CRUD demonstration.',
                  'reviewed_by': 'Operations Team'},
 'complaints': [],
 'customer': {'customer_id': 'TEST_CUSTOMER_001', 'customer_type': 'Consumer'},
 'delivery': {'delivery_completed_at': None,
              'delivery_id': 'TEST_CASE_001',
              'delivery_status': 'Delayed',
              'dispatch_time': None},
 'delivery_id': 'TEST_CASE_001',
 'delivery_status': 'Resolved',
 'hub': {'hub_name': 'Test Hub', 'zone': 'Central'},
 'incidents': [],
 'order': {'order_id': 'TEST_ORDER_001',
           'priority_level': 'High',
           'service_type': 'Test Service'}}

In [27]:
#22 - CRUD-> "DELETE" operation

delete_result = delivery_cases_col.delete_one({"_id": "TEST_CASE_001"})

print("Deleted documents:", delete_result.deleted_count)

check_deleted = delivery_cases_col.find_one({"_id": "TEST_CASE_001"})
print("Document after delete:", check_deleted)

Deleted documents: 1
Document after delete: None

In [28]:
#23 - Query failed deliveries

failed_deliveries = delivery_cases_col.find(
    {"delivery_status": "Failed"},
    {
        "_id": 1,
        "delivery_status": 1,
        "hub.hub_name": 1,
        "hub.zone": 1,
        "driver.driver_id": 1,
        "vehicle.vehicle_id": 1,
        "case_summary": 1
    }
).limit(10)

for doc in failed_deliveries:
    pprint(doc)

{'_id': 'DL00001',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D004'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V056'}}
{'_id': 'DL00010',
 'case_summary': {'app_event_count': 1,
                  'complaint_count': 1,
                  'has_app_events': True,
                  'has_complaint': True,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D058'},
 'hub': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V057'}}
{'_id': 'DL00012',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D051'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V017'}}
{'_id': 'DL00022',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D088'},
 'hub': {'hub_name': 'Riverside Hub', 'zone': 'Riverside'},
 'vehicle': {'vehicle_id': 'V011'}}
{'_id': 'DL00026',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D092'},
 'hub': {'hub_name': 'West Gate', 'zone': 'West'},
 'vehicle': {'vehicle_id': 'V055'}}
{'_id': 'DL00033',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D041'},
 'hub': {'hub_name': 'Airport Hub', 'zone': 'Airport'},
 'vehicle': {'vehicle_id': 'V075'}}
{'_id': 'DL00038',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D096'},
 'hub': {'hub_name': 'South Link', 'zone': 'South'},
 'vehicle': {'vehicle_id': 'V002'}}
{'_id': 'DL00039',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D090'},
 'hub': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V034'}}
{'_id': 'DL00040',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 1,
                  'has_app_events': False,
                  'has_complaint': True,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D027'},
 'hub': {'hub_name': 'West Gate', 'zone': 'West'},
 'vehicle': {'vehicle_id': 'V036'}}
{'_id': 'DL00041',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 1,
                  'has_app_events': False,
                  'has_complaint': True,
                  'has_incident': False,
                  'incident_count': 0},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D100'},
 'hub': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V057'}}

In [29]:
#24 - Query delayed deliveries with complaints

delayed_with_complaints = delivery_cases_col.find(
    {
        "delivery_status": "Delayed",
        "case_summary.has_complaint": True
    },
    {
        "_id": 1,
        "delivery_status": 1,
        "customer.customer_id": 1,
        "hub.hub_name": 1,
        "complaints.complaint_type": 1,
        "complaints.severity": 1,
        "case_summary.complaint_count": 1
    }
).limit(10)

for doc in delayed_with_complaints:
    pprint(doc)

{'_id': 'DL00028',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Appissue', 'severity': 'Low'}],
 'customer': {'customer_id': 'C0476'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Midtown Relay'}}
{'_id': 'DL00064',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Supportexperience', 'severity': 'High'}],
 'customer': {'customer_id': 'C0543'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'East Dock'}}
{'_id': 'DL00120',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Appissue', 'severity': 'High'}],
 'customer': {'customer_id': 'C0001'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Airport Hub'}}
{'_id': 'DL00168',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Driverbehaviour', 'severity': 'Medium'}],
 'customer': {'customer_id': 'C0146'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'North Exchange'}}
{'_id': 'DL00288',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Billing', 'severity': 'Medium'}],
 'customer': {'customer_id': 'C0208'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'East Dock'}}
{'_id': 'DL00296',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Missedpickup', 'severity': 'Medium'}],
 'customer': {'customer_id': 'C0095'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'East Dock'}}
{'_id': 'DL00306',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Missedpickup', 'severity': 'Low'}],
 'customer': {'customer_id': 'C0575'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Riverside Hub'}}
{'_id': 'DL00315',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Billing', 'severity': 'Medium'}],
 'customer': {'customer_id': 'C0182'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'West Gate'}}
{'_id': 'DL00349',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Missedpickup', 'severity': 'High'}],
 'customer': {'customer_id': 'C0250'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Riverside Hub'}}
{'_id': 'DL00355',
 'case_summary': {'complaint_count': 1},
 'complaints': [{'complaint_type': 'Delay', 'severity': 'Medium'}],
 'customer': {'customer_id': 'C0595'},
 'delivery_status': 'Delayed',
 'hub': {'hub_name': 'Riverside Hub'}}

In [30]:
#25 - Aggregation query for hub performance

hub_performance_pipeline = [
    {
        "$group": {
            "_id": {
                "hub_name": "$hub.hub_name",
                "zone": "$hub.zone"
            },
            "total_deliveries": {"$sum": 1},
            "failed_deliveries": {
                "$sum": {
                    "$cond": [{"$eq": ["$delivery_status", "Failed"]}, 1, 0]
                }
            },
            "delayed_deliveries": {
                "$sum": {
                    "$cond": [{"$eq": ["$delivery_status", "Delayed"]}, 1, 0]
                }
            },
            "total_complaints": {
                "$sum": {
                    "$size": {
                        "$ifNull": ["$complaints", []]
                    }
                }
            },
            "avg_customer_rating": {
                "$avg": "$customer_rating_post_delivery"
            }
        }
    },
    {
        "$addFields": {
            "failure_rate": {
                "$round": [
                    {
                        "$multiply": [
                            {"$divide": ["$failed_deliveries", "$total_deliveries"]},
                            100
                        ]
                    },
                    2
                ]
            },
            "delay_rate": {
                "$round": [
                    {
                        "$multiply": [
                            {"$divide": ["$delayed_deliveries", "$total_deliveries"]},
                            100
                        ]
                    },
                    2
                ]
            }
        }
    },
    {
        "$sort": {
            "failure_rate": -1,
            "delayed_deliveries": -1
        }
    }
]

hub_performance_results = list(delivery_cases_col.aggregate(hub_performance_pipeline))

hub_performance_df = pd.json_normalize(hub_performance_results)

display(hub_performance_df)

,total_deliveries,failed_deliveries,delayed_deliveries,total_complaints,avg_customer_rating,failure_rate,delay_rate,_id.hub_name,_id.zone
0,128,26,22,35,3.888203,20.31,17.19,Midtown Relay,Central
1,115,23,25,30,3.676000,20.00,21.74,Central Core,Central
2,104,15,27,23,3.883654,14.42,25.96,Airport Hub,Airport
3,127,16,28,28,3.916457,12.60,22.05,West Gate,West
4,136,17,26,32,3.842059,12.50,19.12,North Exchange,North
5,115,14,25,33,3.884609,12.17,21.74,Riverside Hub,Riverside
6,106,10,26,18,3.951792,9.43,24.53,South Link,South
7,119,11,23,33,3.899496,9.24,19.33,East Dock,East

In [31]:
#26 - Complaint impact by delivery status

complaint_impact_pipeline = [
    {
        "$group": {
            "_id": "$delivery_status",
            "total_deliveries": {"$sum": 1},
            "deliveries_with_complaints": {
                "$sum": {
                    "$cond": ["$case_summary.has_complaint", 1, 0]
                }
            },
            "total_complaints": {
                "$sum": {
                    "$size": {
                        "$ifNull": ["$complaints", []]
                    }
                }
            },
            "avg_rating": {
                "$avg": "$customer_rating_post_delivery"
            }
        }
    },
    {
        "$addFields": {
            "complaint_rate": {
                "$round": [
                    {
                        "$multiply": [
                            {"$divide": ["$deliveries_with_complaints", "$total_deliveries"]},
                            100
                        ]
                    },
                    2
                ]
            }
        }
    },
    {
        "$sort": {
            "complaint_rate": -1
        }
    }
]

complaint_impact_results = list(delivery_cases_col.aggregate(complaint_impact_pipeline))

complaint_impact_df = pd.DataFrame(complaint_impact_results)
display(complaint_impact_df)

,_id,total_deliveries,deliveries_with_complaints,total_complaints,avg_rating,complaint_rate
0,Failed,132,33,35,3.056818,25.00
1,Delayed,202,45,48,3.137871,22.28
2,Ontime,616,131,149,4.280114,21.27

In [32]:
#27 - Incident severity impact on delivery outcomes

incident_pipeline = [
    {
        "$unwind": "$incidents"
    },
    {
        "$group": {
            "_id": {
                "delivery_status": "$delivery_status",
                "incident_type": "$incidents.incident_type",
                "severity": "$incidents.severity"
            },
            "total_incidents": {"$sum": 1},
            "avg_resolved_hours": {"$avg": "$incidents.resolved_hours"}
        }
    },
    {
        "$sort": {
            "total_incidents": -1
        }
    }
]

incident_results = list(delivery_cases_col.aggregate(incident_pipeline))

incident_df = pd.json_normalize(incident_results)

display(incident_df)

,total_incidents,avg_resolved_hours,_id.delivery_status,_id.incident_type,_id.severity
0,14,11.114286,Ontime,Proofmissing,Medium
1,13,15.476923,Ontime,Routedeviation,Low
2,13,14.353846,Ontime,Customernoshow,Low
3,12,4.750000,Ontime,Vehiclefault,Medium
4,10,11.020000,Ontime,Batteryalert,Medium
...,...,...,...,...,...
67,1,11.400000,Delayed,Proofmissing,Medium
68,1,26.700000,Delayed,Vehiclefault,Critical
69,1,6.500000,Delayed,Safetynearmiss,High
70,1,17.300000,Delayed,Safetynearmiss,Medium
71,1,9.100000,Delayed,Vehiclefault,High

In [33]:
#28 - App event failure analysis

app_event_pipeline = [
    {
        "$group": {
            "_id": "$event_details.event_type",
            "total_events": {"$sum": 1},
            "failed_events": {
                "$sum": {
                    "$cond": [{"$eq": ["$event_details.success_flag", 0]}, 1, 0]
                }
            },
            "successful_events": {
                "$sum": {
                    "$cond": [{"$eq": ["$event_details.success_flag", 1]}, 1, 0]
                }
            },
            "avg_api_latency": {
                "$avg": "$event_details.api_latency_ms"
            }
        }
    },
    {
        "$addFields": {
            "failure_rate": {
                "$round": [
                    {
                        "$multiply": [
                            {"$divide": ["$failed_events", "$total_events"]},
                            100
                        ]
                    },
                    2
                ]
            },
            "avg_api_latency": {
                "$round": ["$avg_api_latency", 2]
            }
        }
    },
    {
        "$sort": {
            "failure_rate": -1,
            "avg_api_latency": -1
        }
    }
]

app_event_results = list(app_events_col.aggregate(app_event_pipeline))

app_event_df = pd.DataFrame(app_event_results)

display(app_event_df)

,_id,total_events,failed_events,successful_events,avg_api_latency,failure_rate
0,chat_escalated,38,19,19,478.13,50.00
1,payment_retry,69,19,50,472.68,27.54
2,delivery_instruction_update,75,0,75,496.29,0.00
3,chat_opened,88,0,88,478.33,0.00
4,track_order,138,0,138,460.71,0.00
5,search_route,99,0,99,456.51,0.00
6,eta_refresh,105,0,105,452.15,0.00
7,cancel_attempt,28,0,28,417.14,0.00

In [34]:
#29 - Identify high-risk delivery cases

high_risk_cases = delivery_cases_col.find(
    {
        "$or": [
            {"delivery_status": "Failed"},
            {"delivery_status": "Delayed"},
            {"case_summary.has_incident": True},
            {"case_summary.has_complaint": True}
        ]
    },
    {
        "_id": 1,
        "delivery_status": 1,
        "hub.hub_name": 1,
        "hub.zone": 1,
        "customer.customer_id": 1,
        "driver.driver_id": 1,
        "vehicle.vehicle_id": 1,
        "case_summary": 1
    }
).limit(15)

for case in high_risk_cases:
    pprint(case)

{'_id': 'DL00001',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0567'},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D004'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V056'}}
{'_id': 'DL00004',
 'case_summary': {'app_event_count': 1,
                  'complaint_count': 0,
                  'has_app_events': True,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0616'},
 'delivery_status': 'Delayed',
 'driver': {'driver_id': 'D116'},
 'hub': {'hub_name': 'South Link', 'zone': 'South'},
 'vehicle': {'vehicle_id': 'V055'}}
{'_id': 'DL00006',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0366'},
 'delivery_status': 'Delayed',
 'driver': {'driver_id': 'D037'},
 'hub': {'hub_name': 'East Dock', 'zone': 'East'},
 'vehicle': {'vehicle_id': 'V098'}}
{'_id': 'DL00007',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0303'},
 'delivery_status': 'Delayed',
 'driver': {'driver_id': 'D151'},
 'hub': {'hub_name': 'Riverside Hub', 'zone': 'Riverside'},
 'vehicle': {'vehicle_id': 'V037'}}
{'_id': 'DL00009',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 2},
 'customer': {'customer_id': 'C0560'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D088'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V029'}}
{'_id': 'DL00010',
 'case_summary': {'app_event_count': 1,
                  'complaint_count': 1,
                  'has_app_events': True,
                  'has_complaint': True,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0186'},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D058'},
 'hub': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V057'}}
{'_id': 'DL00011',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 1,
                  'has_app_events': False,
                  'has_complaint': True,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0449'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D074'},
 'hub': {'hub_name': 'West Gate', 'zone': 'West'},
 'vehicle': {'vehicle_id': 'V117'}}
{'_id': 'DL00012',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0197'},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D051'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V017'}}
{'_id': 'DL00013',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0578'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D105'},
 'hub': {'hub_name': 'West Gate', 'zone': 'West'},
 'vehicle': {'vehicle_id': 'V085'}}
{'_id': 'DL00014',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0153'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D102'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V008'}}
{'_id': 'DL00016',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0006'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D010'},
 'hub': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V091'}}
{'_id': 'DL00017',
 'case_summary': {'app_event_count': 1,
                  'complaint_count': 0,
                  'has_app_events': True,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0572'},
 'delivery_status': 'Delayed',
 'driver': {'driver_id': 'D002'},
 'hub': {'hub_name': 'Central Core', 'zone': 'Central'},
 'vehicle': {'vehicle_id': 'V008'}}
{'_id': 'DL00019',
 'case_summary': {'app_event_count': 1,
                  'complaint_count': 0,
                  'has_app_events': True,
                  'has_complaint': False,
                  'has_incident': True,
                  'incident_count': 1},
 'customer': {'customer_id': 'C0336'},
 'delivery_status': 'Ontime',
 'driver': {'driver_id': 'D026'},
 'hub': {'hub_name': 'Airport Hub', 'zone': 'Airport'},
 'vehicle': {'vehicle_id': 'V004'}}
{'_id': 'DL00022',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0492'},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D088'},
 'hub': {'hub_name': 'Riverside Hub', 'zone': 'Riverside'},
 'vehicle': {'vehicle_id': 'V011'}}
{'_id': 'DL00026',
 'case_summary': {'app_event_count': 0,
                  'complaint_count': 0,
                  'has_app_events': False,
                  'has_complaint': False,
                  'has_incident': False,
                  'incident_count': 0},
 'customer': {'customer_id': 'C0480'},
 'delivery_status': 'Failed',
 'driver': {'driver_id': 'D092'},
 'hub': {'hub_name': 'West Gate', 'zone': 'West'},
 'vehicle': {'vehicle_id': 'V055'}}

In [35]:
#30 - Save MongoDB query outputs

hub_performance_df.to_csv("MongoDB_Hub_Performance.csv", index=False)
complaint_impact_df.to_csv("MongoDB_Complaint_Impact.csv", index=False)
incident_df.to_csv("MongoDB_Incident_Impact.csv", index=False)
app_event_df.to_csv("MongoDB_App_Event_Analysis.csv", index=False)

print("MongoDB query outputs saved successfully.")

MongoDB query outputs saved successfully.

In [36]:
#31 - Final MongoDB development summary

print("MongoDB Development Completed")
print("--------------------------------")
print("Database Name:", db.name)
print("Collections:", db.list_collection_names())
print("delivery_cases count:", delivery_cases_col.count_documents({}))
print("customers count:", customers_col.count_documents({}))
print("hubs count:", hubs_col.count_documents({}))
print("app_events count:", app_events_col.count_documents({}))

print("\nNoSQL design used:")
print("1. delivery_cases - nested operational case documents")
print("2. customers - customer profile and service summary")
print("3. hubs - hub profile and performance summary")
print("4. app_events - flexible platform event records")

print("\nMongoDB development section completed successfully.")

MongoDB Development Completed
--------------------------------
Database Name: NorthStar_Mobility_DB
Collections: ['customers', 'delivery_cases', 'hubs', 'app_events']
delivery_cases count: 950
customers count: 650
hubs count: 8
app_events count: 640

NoSQL design used:
1. delivery_cases - nested operational case documents
2. customers - customer profile and service summary
3. hubs - hub profile and performance summary
4. app_events - flexible platform event records

MongoDB development section completed successfully.

# **QUERY  OPTIMISATION**

In [38]:
#32 - Check current MongoDB indexes before optimisation

print("Indexes in delivery_cases collection:")
pprint(list(delivery_cases_col.list_indexes()))

print("\nIndexes in app_events collection:")
pprint(list(app_events_col.list_indexes()))

print("\nIndexes in hubs collection:")
pprint(list(hubs_col.list_indexes()))

Indexes in delivery_cases collection:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')])]

Indexes in app_events collection:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')])]

Indexes in hubs collection:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')])]

In [39]:
#33 - Helper function to run MongoDB explain plan

def run_explain(collection_name, filter_query, projection=None, limit=0):
    """
    Runs explain plan with executionStats for a MongoDB find query.
    """
    command = {
        "find": collection_name,
        "filter": filter_query
    }

    if projection is not None:
        command["projection"] = projection

    if limit > 0:
        command["limit"] = limit

    explain_result = db.command(
        "explain",
        command,
        verbosity="executionStats"
    )

    execution_stats = explain_result.get("executionStats", {})

    summary = {
        "collection": collection_name,
        "filter": filter_query,
        "execution_time_ms": execution_stats.get("executionTimeMillis"),
        "total_docs_examined": execution_stats.get("totalDocsExamined"),
        "total_keys_examined": execution_stats.get("totalKeysExamined"),
        "n_returned": execution_stats.get("nReturned")
    }

    return summary, explain_result

In [40]:
#34 - Run query performance test BEFORE indexing

before_results = []

# Query 1: Find failed deliveries
q1_filter = {"delivery_status": "Failed"}
q1_projection = {
    "_id": 1,
    "delivery_status": 1,
    "hub.hub_name": 1,
    "hub.zone": 1
}

summary_q1_before, explain_q1_before = run_explain(
    "delivery_cases",
    q1_filter,
    q1_projection
)
before_results.append({"query": "Failed deliveries", **summary_q1_before})


# Query 2: Find delayed deliveries with complaints
q2_filter = {
    "delivery_status": "Delayed",
    "case_summary.has_complaint": True
}
q2_projection = {
    "_id": 1,
    "delivery_status": 1,
    "case_summary.complaint_count": 1,
    "hub.hub_name": 1
}

summary_q2_before, explain_q2_before = run_explain(
    "delivery_cases",
    q2_filter,
    q2_projection
)
before_results.append({"query": "Delayed deliveries with complaints", **summary_q2_before})


# Query 3: Find poor service cases by hub zone
q3_filter = {
    "hub.zone": "Central",
    "delivery_status": {"$in": ["Failed", "Delayed"]}
}
q3_projection = {
    "_id": 1,
    "delivery_status": 1,
    "hub.hub_name": 1,
    "hub.zone": 1
}

summary_q3_before, explain_q3_before = run_explain(
    "delivery_cases",
    q3_filter,
    q3_projection
)
before_results.append({"query": "Poor service cases by zone", **summary_q3_before})


# Query 4: App event failures
q4_filter = {
    "event_details.success_flag": 0
}
q4_projection = {
    "_id": 1,
    "event_details.event_type": 1,
    "event_details.success_flag": 1,
    "event_details.api_latency_ms": 1
}

summary_q4_before, explain_q4_before = run_explain(
    "app_events",
    q4_filter,
    q4_projection
)
before_results.append({"query": "Failed app events", **summary_q4_before})


before_df = pd.DataFrame(before_results)
display(before_df)

,query,collection,filter,execution_time_ms,total_docs_examined,total_keys_examined,n_returned
0,Failed deliveries,delivery_cases,{'delivery_status': 'Failed'},1,950,0,132
1,Delayed deliveries with complaints,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",1,950,0,45
2,Poor service cases by zone,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",1,950,0,96
3,Failed app events,app_events,{'event_details.success_flag': 0},0,640,0,38

In [41]:
#35 - Create indexes for query optimisation

# Index 1: Optimise delivery status searches
delivery_cases_col.create_index(
    [("delivery_status", 1)],
    name="idx_delivery_status"
)

# Index 2: Optimise delayed/failed cases with complaints
delivery_cases_col.create_index(
    [("delivery_status", 1), ("case_summary.has_complaint", 1)],
    name="idx_status_complaint"
)

# Index 3: Optimise hub zone and delivery status queries
delivery_cases_col.create_index(
    [("hub.zone", 1), ("delivery_status", 1)],
    name="idx_zone_status"
)

# Index 4: Optimise driver-level delivery performance queries
delivery_cases_col.create_index(
    [("driver.driver_id", 1), ("delivery_status", 1)],
    name="idx_driver_status"
)

# Index 5: Optimise app event failure queries
app_events_col.create_index(
    [("event_details.success_flag", 1), ("event_details.event_type", 1)],
    name="idx_app_success_event_type"
)

# Index 6: Optimise hub performance ranking queries
hubs_col.create_index(
    [("performance_summary.failure_rate", -1)],
    name="idx_hub_failure_rate"
)

print("Indexes created successfully.")

Indexes created successfully.

In [42]:
#36 - Check indexes after optimisation

print("Indexes in delivery_cases collection after optimisation:")
pprint(list(delivery_cases_col.list_indexes()))

print("\nIndexes in app_events collection after optimisation:")
pprint(list(app_events_col.list_indexes()))

print("\nIndexes in hubs collection after optimisation:")
pprint(list(hubs_col.list_indexes()))

Indexes in delivery_cases collection after optimisation:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')]),
 SON([('v', 2), ('key', SON([('delivery_status', 1)])), ('name', 'idx_delivery_status')]),
 SON([('v', 2), ('key', SON([('delivery_status', 1), ('case_summary.has_complaint', 1)])), ('name', 'idx_status_complaint')]),
 SON([('v', 2), ('key', SON([('hub.zone', 1), ('delivery_status', 1)])), ('name', 'idx_zone_status')]),
 SON([('v', 2), ('key', SON([('driver.driver_id', 1), ('delivery_status', 1)])), ('name', 'idx_driver_status')])]

Indexes in app_events collection after optimisation:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')]),
 SON([('v', 2), ('key', SON([('event_details.success_flag', 1), ('event_details.event_type', 1)])), ('name', 'idx_app_success_event_type')])]

Indexes in hubs collection after optimisation:
[SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')]),
 SON([('v', 2), ('key', SON([('performance_summary.failure_rate', -1)])), ('name', 'idx_hub_failure_rate')])]

In [43]:
#37 - Run query performance test AFTER indexing

after_results = []

summary_q1_after, explain_q1_after = run_explain(
    "delivery_cases",
    q1_filter,
    q1_projection
)
after_results.append({"query": "Failed deliveries", **summary_q1_after})


summary_q2_after, explain_q2_after = run_explain(
    "delivery_cases",
    q2_filter,
    q2_projection
)
after_results.append({"query": "Delayed deliveries with complaints", **summary_q2_after})


summary_q3_after, explain_q3_after = run_explain(
    "delivery_cases",
    q3_filter,
    q3_projection
)
after_results.append({"query": "Poor service cases by zone", **summary_q3_after})


summary_q4_after, explain_q4_after = run_explain(
    "app_events",
    q4_filter,
    q4_projection
)
after_results.append({"query": "Failed app events", **summary_q4_after})


after_df = pd.DataFrame(after_results)
display(after_df)

,query,collection,filter,execution_time_ms,total_docs_examined,total_keys_examined,n_returned
0,Failed deliveries,delivery_cases,{'delivery_status': 'Failed'},2,132,132,132
1,Delayed deliveries with complaints,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",0,45,45,45
2,Poor service cases by zone,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",2,96,97,96
3,Failed app events,app_events,{'event_details.success_flag': 0},1,38,38,38

In [44]:
#38 - Compare query performance before and after indexing

comparison_df = before_df.merge(
    after_df,
    on="query",
    suffixes=("_before", "_after")
)

comparison_df["docs_examined_reduction"] = (
    comparison_df["total_docs_examined_before"] - comparison_df["total_docs_examined_after"]
)

comparison_df["keys_examined_change"] = (
    comparison_df["total_keys_examined_after"] - comparison_df["total_keys_examined_before"]
)

comparison_df["execution_time_change_ms"] = (
    comparison_df["execution_time_ms_before"] - comparison_df["execution_time_ms_after"]
)

display(comparison_df)

,query,collection_before,filter_before,execution_time_ms_before,total_docs_examined_before,total_keys_examined_before,n_returned_before,collection_after,filter_after,execution_time_ms_after,total_docs_examined_after,total_keys_examined_after,n_returned_after,docs_examined_reduction,keys_examined_change,execution_time_change_ms
0,Failed deliveries,delivery_cases,{'delivery_status': 'Failed'},1,950,0,132,delivery_cases,{'delivery_status': 'Failed'},2,132,132,132,818,132,-1
1,Delayed deliveries with complaints,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",1,950,0,45,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",0,45,45,45,905,45,1
2,Poor service cases by zone,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",1,950,0,96,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",2,96,97,96,854,97,-1
3,Failed app events,app_events,{'event_details.success_flag': 0},0,640,0,38,app_events,{'event_details.success_flag': 0},1,38,38,38,602,38,-1

In [45]:
#39 - Display winning query plans after indexing

print("Winning plan for Query 1 - Failed deliveries:")
pprint(explain_q1_after["queryPlanner"]["winningPlan"])

print("\nWinning plan for Query 2 - Delayed deliveries with complaints:")
pprint(explain_q2_after["queryPlanner"]["winningPlan"])

print("\nWinning plan for Query 3 - Poor service cases by zone:")
pprint(explain_q3_after["queryPlanner"]["winningPlan"])

print("\nWinning plan for Query 4 - Failed app events:")
pprint(explain_q4_after["queryPlanner"]["winningPlan"])

Winning plan for Query 1 - Failed deliveries:
{'inputStage': {'inputStage': {'direction': 'forward',
                               'indexBounds': {'delivery_status': ['["Failed", '
                                                                   '"Failed"]']},
                               'indexName': 'idx_delivery_status',
                               'indexVersion': 2,
                               'isMultiKey': False,
                               'isPartial': False,
                               'isSparse': False,
                               'isUnique': False,
                               'keyPattern': {'delivery_status': 1},
                               'multiKeyPaths': {'delivery_status': []},
                               'stage': 'IXSCAN'},
                'stage': 'FETCH'},
 'isCached': False,
 'stage': 'PROJECTION_DEFAULT',
 'transformBy': {'_id': 1,
                 'delivery_status': 1,
                 'hub.hub_name': 1,
                 'hub.zone': 1}}

Winning plan for Query 2 - Delayed deliveries with complaints:
{'inputStage': {'inputStage': {'direction': 'forward',
                               'indexBounds': {'case_summary.has_complaint': ['[true, '
                                                                              'true]'],
                                               'delivery_status': ['["Delayed", '
                                                                   '"Delayed"]']},
                               'indexName': 'idx_status_complaint',
                               'indexVersion': 2,
                               'isMultiKey': False,
                               'isPartial': False,
                               'isSparse': False,
                               'isUnique': False,
                               'keyPattern': {'case_summary.has_complaint': 1,
                                              'delivery_status': 1},
                               'multiKeyPaths': {'case_summary.has_complaint': [],
                                                 'delivery_status': []},
                               'stage': 'IXSCAN'},
                'stage': 'FETCH'},
 'isCached': False,
 'stage': 'PROJECTION_DEFAULT',
 'transformBy': {'_id': 1,
                 'case_summary.complaint_count': 1,
                 'delivery_status': 1,
                 'hub.hub_name': 1}}

Winning plan for Query 3 - Poor service cases by zone:
{'inputStage': {'inputStage': {'direction': 'forward',
                               'indexBounds': {'delivery_status': ['["Delayed", '
                                                                   '"Delayed"]',
                                                                   '["Failed", '
                                                                   '"Failed"]'],
                                               'hub.zone': ['["Central", '
                                                            '"Central"]']},
                               'indexName': 'idx_zone_status',
                               'indexVersion': 2,
                               'isMultiKey': False,
                               'isPartial': False,
                               'isSparse': False,
                               'isUnique': False,
                               'keyPattern': {'delivery_status': 1,
                                              'hub.zone': 1},
                               'multiKeyPaths': {'delivery_status': [],
                                                 'hub.zone': []},
                               'stage': 'IXSCAN'},
                'stage': 'FETCH'},
 'isCached': False,
 'stage': 'PROJECTION_DEFAULT',
 'transformBy': {'_id': 1,
                 'delivery_status': 1,
                 'hub.hub_name': 1,
                 'hub.zone': 1}}

Winning plan for Query 4 - Failed app events:
{'inputStage': {'inputStage': {'direction': 'forward',
                               'indexBounds': {'event_details.event_type': ['[MinKey, '
                                                                            'MaxKey]'],
                                               'event_details.success_flag': ['[0, '
                                                                              '0]']},
                               'indexName': 'idx_app_success_event_type',
                               'indexVersion': 2,
                               'isMultiKey': False,
                               'isPartial': False,
                               'isSparse': False,
                               'isUnique': False,
                               'keyPattern': {'event_details.event_type': 1,
                                              'event_details.success_flag': 1},
                               'multiKeyPaths': {'event_details.event_type': [],
                                                 'event_details.success_flag': []},
                               'stage': 'IXSCAN'},
                'stage': 'FETCH'},
 'isCached': False,
 'stage': 'PROJECTION_DEFAULT',
 'transformBy': {'_id': 1,
                 'event_details.api_latency_ms': 1,
                 'event_details.event_type': 1,
                 'event_details.success_flag': 1}}

In [46]:
#40 - Query optimised hub performance ranking

optimised_hub_query = hubs_col.find(
    {},
    {
        "_id": 1,
        "hub_profile.hub_name": 1,
        "hub_profile.zone": 1,
        "performance_summary.total_deliveries": 1,
        "performance_summary.failed_deliveries": 1,
        "performance_summary.failure_rate": 1
    }
).sort("performance_summary.failure_rate", -1).limit(10)

for hub in optimised_hub_query:
    pprint(hub)

{'_id': 'H08',
 'hub_profile': {'hub_name': 'Midtown Relay', 'zone': 'Central'},
 'performance_summary': {'failed_deliveries': 26,
                         'failure_rate': 20.31,
                         'total_deliveries': 128}}
{'_id': 'H05',
 'hub_profile': {'hub_name': 'Central Core', 'zone': 'Central'},
 'performance_summary': {'failed_deliveries': 23,
                         'failure_rate': 20.0,
                         'total_deliveries': 115}}
{'_id': 'H06',
 'hub_profile': {'hub_name': 'Airport Hub', 'zone': 'Airport'},
 'performance_summary': {'failed_deliveries': 15,
                         'failure_rate': 14.42,
                         'total_deliveries': 104}}
{'_id': 'H04',
 'hub_profile': {'hub_name': 'West Gate', 'zone': 'West'},
 'performance_summary': {'failed_deliveries': 16,
                         'failure_rate': 12.6,
                         'total_deliveries': 127}}
{'_id': 'H01',
 'hub_profile': {'hub_name': 'North Exchange', 'zone': 'North'},
 'performance_summary': {'failed_deliveries': 17,
                         'failure_rate': 12.5,
                         'total_deliveries': 136}}
{'_id': 'H07',
 'hub_profile': {'hub_name': 'Riverside Hub', 'zone': 'Riverside'},
 'performance_summary': {'failed_deliveries': 14,
                         'failure_rate': 12.17,
                         'total_deliveries': 115}}
{'_id': 'H02',
 'hub_profile': {'hub_name': 'South Link', 'zone': 'South'},
 'performance_summary': {'failed_deliveries': 10,
                         'failure_rate': 9.43,
                         'total_deliveries': 106}}
{'_id': 'H03',
 'hub_profile': {'hub_name': 'East Dock', 'zone': 'East'},
 'performance_summary': {'failed_deliveries': 11,
                         'failure_rate': 9.24,
                         'total_deliveries': 119}}

In [47]:
#41 - Save query optimisation outputs

before_df.to_csv("Query_Optimisation_Before_Indexing.csv", index=False)
after_df.to_csv("Query_Optimisation_After_Indexing.csv", index=False)
comparison_df.to_csv("Query_Optimisation_Comparison.csv", index=False)

print("Query optimisation outputs saved successfully.")

Query optimisation outputs saved successfully.

In [48]:
#42 - Final query optimisation summary

print("Query Optimisation Completed")
print("--------------------------------")

print("Main optimisation techniques used:")
print("1. Single-field index on delivery_status")
print("2. Compound index on delivery_status and complaint flag")
print("3. Compound index on hub zone and delivery status")
print("4. Compound index on driver and delivery status")
print("5. Compound index on app event success flag and event type")
print("6. Descending index on hub failure rate")

print("\nBefore and after query performance comparison:")
display(comparison_df)

print("\nQuery optimisation section completed successfully.")

Query Optimisation Completed
--------------------------------
Main optimisation techniques used:
1. Single-field index on delivery_status
2. Compound index on delivery_status and complaint flag
3. Compound index on hub zone and delivery status
4. Compound index on driver and delivery status
5. Compound index on app event success flag and event type
6. Descending index on hub failure rate

Before and after query performance comparison:

,query,collection_before,filter_before,execution_time_ms_before,total_docs_examined_before,total_keys_examined_before,n_returned_before,collection_after,filter_after,execution_time_ms_after,total_docs_examined_after,total_keys_examined_after,n_returned_after,docs_examined_reduction,keys_examined_change,execution_time_change_ms
0,Failed deliveries,delivery_cases,{'delivery_status': 'Failed'},1,950,0,132,delivery_cases,{'delivery_status': 'Failed'},2,132,132,132,818,132,-1
1,Delayed deliveries with complaints,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",1,950,0,45,delivery_cases,"{'delivery_status': 'Delayed', 'case_summary.h...",0,45,45,45,905,45,1
2,Poor service cases by zone,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",1,950,0,96,delivery_cases,"{'hub.zone': 'Central', 'delivery_status': {'$...",2,96,97,96,854,97,-1
3,Failed app events,app_events,{'event_details.success_flag': 0},0,640,0,38,app_events,{'event_details.success_flag': 0},1,38,38,38,602,38,-1

Query optimisation section completed successfully.